<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\Department;
use App\Models\Province;
use App\Models\CantonDistrict;
use App\Models\NeighborhoodCommunity;
use App\Models\Municipality;
use Illuminate\Support\Str;

class BermejoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Distritos

        $CantonDistrict1= new CantonDistrict(); $CantonDistrict1->municipality_id=11; $CantonDistrict1->type='DISTRITO'; $CantonDistrict1->name = 'DISTRITO 1';$CantonDistrict1->description='DISTRITO: 1';$CantonDistrict1->state = 'ACTIVE'; $CantonDistrict1->slug = Str::uuid();$CantonDistrict1->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict1->save();
        $CantonDistrict2= new CantonDistrict(); $CantonDistrict2->municipality_id=11; $CantonDistrict2->type='DISTRITO'; $CantonDistrict2->name = 'DISTRITO 2';$CantonDistrict2->description='DISTRITO: 2';$CantonDistrict2->state = 'ACTIVE'; $CantonDistrict2->slug = Str::uuid();$CantonDistrict2->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict2->save();
        $CantonDistrict3= new CantonDistrict(); $CantonDistrict3->municipality_id=11; $CantonDistrict3->type='DISTRITO'; $CantonDistrict3->name = 'DISTRITO 3';$CantonDistrict3->description='DISTRITO: 3';$CantonDistrict3->state = 'ACTIVE'; $CantonDistrict3->slug = Str::uuid();$CantonDistrict3->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict3->save();
        $CantonDistrict4= new CantonDistrict(); $CantonDistrict4->municipality_id=11; $CantonDistrict4->type='DISTRITO'; $CantonDistrict4->name = 'DISTRITO 4';$CantonDistrict4->description='DISTRITO: 4';$CantonDistrict4->state = 'ACTIVE'; $CantonDistrict4->slug = Str::uuid();$CantonDistrict4->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict4->save();
        $CantonDistrict5= new CantonDistrict(); $CantonDistrict5->municipality_id=11; $CantonDistrict5->type='DISTRITO'; $CantonDistrict5->name = 'DISTRITO 5';$CantonDistrict5->description='DISTRITO: 5';$CantonDistrict5->state = 'ACTIVE'; $CantonDistrict5->slug = Str::uuid();$CantonDistrict5->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict5->save();
        $CantonDistrict6= new CantonDistrict(); $CantonDistrict6->municipality_id=11; $CantonDistrict6->type='DISTRITO'; $CantonDistrict6->name = 'DISTRITO 6';$CantonDistrict6->description='DISTRITO: 6';$CantonDistrict6->state = 'ACTIVE'; $CantonDistrict6->slug = Str::uuid();$CantonDistrict6->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict6->save();
        $CantonDistrict7= new CantonDistrict(); $CantonDistrict7->municipality_id=11; $CantonDistrict7->type='DISTRITO'; $CantonDistrict7->name = 'DISTRITO 7';$CantonDistrict7->description='DISTRITO: 7';$CantonDistrict7->state = 'ACTIVE'; $CantonDistrict7->slug = Str::uuid();$CantonDistrict7->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict7->save();
        $CantonDistrict8= new CantonDistrict(); $CantonDistrict8->municipality_id=11; $CantonDistrict8->type='DISTRITO'; $CantonDistrict8->name = 'DISTRITO 8';$CantonDistrict8->description='DISTRITO: 8';$CantonDistrict8->state = 'ACTIVE'; $CantonDistrict8->slug = Str::uuid();$CantonDistrict8->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict8->save();
        $CantonDistrict9= new CantonDistrict(); $CantonDistrict9->municipality_id=11; $CantonDistrict9->type='DISTRITO'; $CantonDistrict9->name = 'DISTRITO 9';$CantonDistrict9->description='DISTRITO: 9';$CantonDistrict9->state = 'ACTIVE'; $CantonDistrict9->slug = Str::uuid();$CantonDistrict9->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $CantonDistrict9->save();

        //Barrios o Comunidades

        $NeighborhoodCommunity1= new NeighborhoodCommunity(); $NeighborhoodCommunity1->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity1->name = 'MUNICIPAL'; $NeighborhoodCommunity1 ->description='BARRIO'; $NeighborhoodCommunity1->type = 'BARRIO'; $NeighborhoodCommunity1->state = 'ACTIVE'; $NeighborhoodCommunity1->slug = Str::uuid();$NeighborhoodCommunity1->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity1->save();
        $NeighborhoodCommunity2= new NeighborhoodCommunity(); $NeighborhoodCommunity2->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity2->name = 'JUAN PABLO II'; $NeighborhoodCommunity2 ->description='BARRIO'; $NeighborhoodCommunity2->type = 'BARRIO'; $NeighborhoodCommunity2->state = 'ACTIVE'; $NeighborhoodCommunity2->slug = Str::uuid();$NeighborhoodCommunity2->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity2->save();
        $NeighborhoodCommunity3= new NeighborhoodCommunity(); $NeighborhoodCommunity3->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity3->name = 'VICTOR PAZ'; $NeighborhoodCommunity3 ->description='BARRIO'; $NeighborhoodCommunity3->type = 'BARRIO'; $NeighborhoodCommunity3->state = 'ACTIVE'; $NeighborhoodCommunity3->slug = Str::uuid();$NeighborhoodCommunity3->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity3->save();
        $NeighborhoodCommunity4= new NeighborhoodCommunity(); $NeighborhoodCommunity4->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity4->name = '21 DE DICIEMBRE'; $NeighborhoodCommunity4 ->description='BARRIO'; $NeighborhoodCommunity4->type = 'BARRIO'; $NeighborhoodCommunity4->state = 'ACTIVE'; $NeighborhoodCommunity4->slug = Str::uuid();$NeighborhoodCommunity4->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity4->save();
        $NeighborhoodCommunity5= new NeighborhoodCommunity(); $NeighborhoodCommunity5->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity5->name = '27 DE MAYO'; $NeighborhoodCommunity5 ->description='BARRIO'; $NeighborhoodCommunity5->type = 'BARRIO'; $NeighborhoodCommunity5->state = 'ACTIVE'; $NeighborhoodCommunity5->slug = Str::uuid();$NeighborhoodCommunity5->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity5->save();
        $NeighborhoodCommunity6= new NeighborhoodCommunity(); $NeighborhoodCommunity6->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity6->name = 'Y.P.F.B'; $NeighborhoodCommunity6 ->description='BARRIO'; $NeighborhoodCommunity6->type = 'BARRIO'; $NeighborhoodCommunity6->state = 'ACTIVE'; $NeighborhoodCommunity6->slug = Str::uuid();$NeighborhoodCommunity6->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity6->save();
        $NeighborhoodCommunity7= new NeighborhoodCommunity(); $NeighborhoodCommunity7->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity7->name = 'PETROLERO'; $NeighborhoodCommunity7 ->description='BARRIO'; $NeighborhoodCommunity7->type = 'BARRIO'; $NeighborhoodCommunity7->state = 'ACTIVE'; $NeighborhoodCommunity7->slug = Str::uuid();$NeighborhoodCommunity7->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f';$NeighborhoodCommunity7->save();
        $NeighborhoodCommunity8= new NeighborhoodCommunity(); $NeighborhoodCommunity8->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity8->name = 'CENTRAL'; $NeighborhoodCommunity8 ->description='BARRIO'; $NeighborhoodCommunity8->type = 'BARRIO'; $NeighborhoodCommunity8->state = 'ACTIVE'; $NeighborhoodCommunity8->slug = Str::uuid();$NeighborhoodCommunity8->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity8->save();
        $NeighborhoodCommunity9= new NeighborhoodCommunity(); $NeighborhoodCommunity9->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity9->name = 'LINDO'; $NeighborhoodCommunity9 ->description='BARRIO'; $NeighborhoodCommunity9->type = 'BARRIO'; $NeighborhoodCommunity9->state = 'ACTIVE'; $NeighborhoodCommunity9->slug = Str::uuid();$NeighborhoodCommunity9->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity9->save();
        $NeighborhoodCommunity10= new NeighborhoodCommunity(); $NeighborhoodCommunity10->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity10->name = 'ANICETO ARCE'; $NeighborhoodCommunity10 ->description='BARRIO'; $NeighborhoodCommunity10->type = 'BARRIO'; $NeighborhoodCommunity10->state = 'ACTIVE'; $NeighborhoodCommunity10->slug = Str::uuid();$NeighborhoodCommunity10->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity10->save();
        $NeighborhoodCommunity11= new NeighborhoodCommunity(); $NeighborhoodCommunity11->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity11->name = 'BOLIVAR'; $NeighborhoodCommunity11 ->description='BARRIO'; $NeighborhoodCommunity11->type = 'BARRIO'; $NeighborhoodCommunity11->state = 'ACTIVE'; $NeighborhoodCommunity11->slug = Str::uuid();$NeighborhoodCommunity11->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity11->save();
        $NeighborhoodCommunity12= new NeighborhoodCommunity(); $NeighborhoodCommunity12->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity12->name = 'AVAROA'; $NeighborhoodCommunity12 ->description='BARRIO'; $NeighborhoodCommunity12->type = 'BARRIO'; $NeighborhoodCommunity12->state = 'ACTIVE'; $NeighborhoodCommunity12->slug = Str::uuid();$NeighborhoodCommunity12->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity12->save();
        $NeighborhoodCommunity13= new NeighborhoodCommunity(); $NeighborhoodCommunity13->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity13->name = 'LAPACHO'; $NeighborhoodCommunity13 ->description='BARRIO'; $NeighborhoodCommunity13->type = 'BARRIO'; $NeighborhoodCommunity13->state = 'ACTIVE'; $NeighborhoodCommunity13->slug = Str::uuid();$NeighborhoodCommunity13->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity13->save();
        $NeighborhoodCommunity14= new NeighborhoodCommunity(); $NeighborhoodCommunity14->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity14->name = '1° DE  MAYO'; $NeighborhoodCommunity14 ->description='BARRIO'; $NeighborhoodCommunity14->type = 'BARRIO'; $NeighborhoodCommunity14->state = 'ACTIVE'; $NeighborhoodCommunity14->slug = Str::uuid();$NeighborhoodCommunity14->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity14->save();
        $NeighborhoodCommunity15= new NeighborhoodCommunity(); $NeighborhoodCommunity15->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity15->name = 'LUIS DE FUENTES'; $NeighborhoodCommunity15 ->description='BARRIO'; $NeighborhoodCommunity15->type = 'BARRIO'; $NeighborhoodCommunity15->state = 'ACTIVE'; $NeighborhoodCommunity15->slug = Str::uuid();$NeighborhoodCommunity15->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity15->save();
        $NeighborhoodCommunity16= new NeighborhoodCommunity(); $NeighborhoodCommunity16->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity16->name = 'PARAISO'; $NeighborhoodCommunity16 ->description='BARRIO'; $NeighborhoodCommunity16->type = 'BARRIO'; $NeighborhoodCommunity16->state = 'ACTIVE'; $NeighborhoodCommunity16->slug = Str::uuid();$NeighborhoodCommunity16->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity16->save();
        $NeighborhoodCommunity17= new NeighborhoodCommunity(); $NeighborhoodCommunity17->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity17->name = 'AEROPUERTO'; $NeighborhoodCommunity17 ->description='BARRIO'; $NeighborhoodCommunity17->type = 'BARRIO'; $NeighborhoodCommunity17->state = 'ACTIVE'; $NeighborhoodCommunity17->slug = Str::uuid();$NeighborhoodCommunity17->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity17->save();
        $NeighborhoodCommunity18= new NeighborhoodCommunity(); $NeighborhoodCommunity18->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity18->name = 'MIRAFLORES'; $NeighborhoodCommunity18 ->description='BARRIO'; $NeighborhoodCommunity18->type = 'BARRIO'; $NeighborhoodCommunity18->state = 'ACTIVE'; $NeighborhoodCommunity18->slug = Str::uuid();$NeighborhoodCommunity18->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity18->save();
        $NeighborhoodCommunity19= new NeighborhoodCommunity(); $NeighborhoodCommunity19->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity19->name = 'SAN JOSE'; $NeighborhoodCommunity19 ->description='BARRIO'; $NeighborhoodCommunity19->type = 'BARRIO'; $NeighborhoodCommunity19->state = 'ACTIVE'; $NeighborhoodCommunity19->slug = Str::uuid();$NeighborhoodCommunity19->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity19->save();
        $NeighborhoodCommunity20= new NeighborhoodCommunity(); $NeighborhoodCommunity20->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity20->name = '15 DE ABRIL'; $NeighborhoodCommunity20 ->description='BARRIO'; $NeighborhoodCommunity20->type = 'BARRIO'; $NeighborhoodCommunity20->state = 'ACTIVE'; $NeighborhoodCommunity20->slug = Str::uuid();$NeighborhoodCommunity20->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity20->save();
        $NeighborhoodCommunity21= new NeighborhoodCommunity(); $NeighborhoodCommunity21->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity21->name = 'MOTO MENDEZ'; $NeighborhoodCommunity21 ->description='BARRIO'; $NeighborhoodCommunity21->type = 'BARRIO'; $NeighborhoodCommunity21->state = 'ACTIVE'; $NeighborhoodCommunity21->slug = Str::uuid();$NeighborhoodCommunity21->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity21->save();
        $NeighborhoodCommunity22= new NeighborhoodCommunity(); $NeighborhoodCommunity22->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity22->name = 'SAN BERNARDO'; $NeighborhoodCommunity22 ->description='BARRIO'; $NeighborhoodCommunity22->type = 'BARRIO'; $NeighborhoodCommunity22->state = 'ACTIVE'; $NeighborhoodCommunity22->slug = Str::uuid();$NeighborhoodCommunity22->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity22->save();
        $NeighborhoodCommunity23= new NeighborhoodCommunity(); $NeighborhoodCommunity23->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity23->name = 'AZUCARERO'; $NeighborhoodCommunity23 ->description='BARRIO'; $NeighborhoodCommunity23->type = 'BARRIO'; $NeighborhoodCommunity23->state = 'ACTIVE'; $NeighborhoodCommunity23->slug = Str::uuid();$NeighborhoodCommunity23->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity23->save();
        $NeighborhoodCommunity24= new NeighborhoodCommunity(); $NeighborhoodCommunity24->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity24->name = 'LAS PALMERAS'; $NeighborhoodCommunity24 ->description='BARRIO'; $NeighborhoodCommunity24->type = 'BARRIO'; $NeighborhoodCommunity24->state = 'ACTIVE'; $NeighborhoodCommunity24->slug = Str::uuid();$NeighborhoodCommunity24->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity24->save();
        $NeighborhoodCommunity25= new NeighborhoodCommunity(); $NeighborhoodCommunity25->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity25->name = 'SAN ANTONIO'; $NeighborhoodCommunity25 ->description='BARRIO'; $NeighborhoodCommunity25->type = 'BARRIO'; $NeighborhoodCommunity25->state = 'ACTIVE'; $NeighborhoodCommunity25->slug = Str::uuid();$NeighborhoodCommunity25->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity25->save();
        $NeighborhoodCommunity26= new NeighborhoodCommunity(); $NeighborhoodCommunity26->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity26->name = 'CAMP. I.A.B SAN SANTIAGO'; $NeighborhoodCommunity26 ->description='BARRIO'; $NeighborhoodCommunity26->type = 'BARRIO'; $NeighborhoodCommunity26->state = 'ACTIVE'; $NeighborhoodCommunity26->slug = Str::uuid();$NeighborhoodCommunity26->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity26->save();
        $NeighborhoodCommunity27= new NeighborhoodCommunity(); $NeighborhoodCommunity27->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity27->name = 'SAN JUAN'; $NeighborhoodCommunity27 ->description='BARRIO'; $NeighborhoodCommunity27->type = 'BARRIO'; $NeighborhoodCommunity27->state = 'ACTIVE'; $NeighborhoodCommunity27->slug = Str::uuid();$NeighborhoodCommunity27->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity27->save();
        $NeighborhoodCommunity28= new NeighborhoodCommunity(); $NeighborhoodCommunity28->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity28->name = 'PORVENIR'; $NeighborhoodCommunity28 ->description='BARRIO'; $NeighborhoodCommunity28->type = 'BARRIO'; $NeighborhoodCommunity28->state = 'ACTIVE'; $NeighborhoodCommunity28->slug = Str::uuid();$NeighborhoodCommunity28->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity28->save();
        $NeighborhoodCommunity29= new NeighborhoodCommunity(); $NeighborhoodCommunity29->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity29->name = '2 DE AGOSTO'; $NeighborhoodCommunity29 ->description='BARRIO'; $NeighborhoodCommunity29->type = 'BARRIO'; $NeighborhoodCommunity29->state = 'ACTIVE'; $NeighborhoodCommunity29->slug = Str::uuid();$NeighborhoodCommunity29->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity29->save();
        $NeighborhoodCommunity30= new NeighborhoodCommunity(); $NeighborhoodCommunity30->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity30->name = '25 DE ENERO'; $NeighborhoodCommunity30 ->description='COMUNIDAD'; $NeighborhoodCommunity30->type = 'COMUNIDAD'; $NeighborhoodCommunity30->state = 'ACTIVE'; $NeighborhoodCommunity30->slug = Str::uuid();$NeighborhoodCommunity30->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity30->save();
        $NeighborhoodCommunity31= new NeighborhoodCommunity(); $NeighborhoodCommunity31->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity31->name = 'CERCADO'; $NeighborhoodCommunity31 ->description='COMUNIDAD'; $NeighborhoodCommunity31->type = 'COMUNIDAD'; $NeighborhoodCommunity31->state = 'ACTIVE'; $NeighborhoodCommunity31->slug = Str::uuid();$NeighborhoodCommunity31->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity31->save();
        $NeighborhoodCommunity32= new NeighborhoodCommunity(); $NeighborhoodCommunity32->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity32->name = 'EL NUEVE'; $NeighborhoodCommunity32 ->description='COMUNIDAD'; $NeighborhoodCommunity32->type = 'COMUNIDAD'; $NeighborhoodCommunity32->state = 'ACTIVE'; $NeighborhoodCommunity32->slug = Str::uuid();$NeighborhoodCommunity32->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity32->save();
        $NeighborhoodCommunity33= new NeighborhoodCommunity(); $NeighborhoodCommunity33->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity33->name = 'CANDADO CHICO'; $NeighborhoodCommunity33 ->description='COMUNIDAD'; $NeighborhoodCommunity33->type = 'COMUNIDAD'; $NeighborhoodCommunity33->state = 'ACTIVE'; $NeighborhoodCommunity33->slug = Str::uuid();$NeighborhoodCommunity33->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity33->save();
        $NeighborhoodCommunity34= new NeighborhoodCommunity(); $NeighborhoodCommunity34->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity34->name = 'CANDADO GRANDE'; $NeighborhoodCommunity34 ->description='COMUNIDAD'; $NeighborhoodCommunity34->type = 'COMUNIDAD'; $NeighborhoodCommunity34->state = 'ACTIVE'; $NeighborhoodCommunity34->slug = Str::uuid();$NeighborhoodCommunity34->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity34->save();
        $NeighborhoodCommunity35= new NeighborhoodCommunity(); $NeighborhoodCommunity35->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity35->name = 'EL CINCO'; $NeighborhoodCommunity35 ->description='COMUNIDAD'; $NeighborhoodCommunity35->type = 'COMUNIDAD'; $NeighborhoodCommunity35->state = 'ACTIVE'; $NeighborhoodCommunity35->slug = Str::uuid();$NeighborhoodCommunity35->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity35->save();
        $NeighborhoodCommunity36= new NeighborhoodCommunity(); $NeighborhoodCommunity36->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity36->name = 'FLOR DE ORO'; $NeighborhoodCommunity36 ->description='COMUNIDAD'; $NeighborhoodCommunity36->type = 'COMUNIDAD'; $NeighborhoodCommunity36->state = 'ACTIVE'; $NeighborhoodCommunity36->slug = Str::uuid();$NeighborhoodCommunity36->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity36->save();
        $NeighborhoodCommunity37= new NeighborhoodCommunity(); $NeighborhoodCommunity37->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity37->name = 'LA FLORIDA'; $NeighborhoodCommunity37 ->description='COMUNIDAD'; $NeighborhoodCommunity37->type = 'COMUNIDAD'; $NeighborhoodCommunity37->state = 'ACTIVE'; $NeighborhoodCommunity37->slug = Str::uuid();$NeighborhoodCommunity37->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity37->save();
        $NeighborhoodCommunity38= new NeighborhoodCommunity(); $NeighborhoodCommunity38->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity38->name = 'LOS POZOS'; $NeighborhoodCommunity38 ->description='COMUNIDAD'; $NeighborhoodCommunity38->type = 'COMUNIDAD'; $NeighborhoodCommunity38->state = 'ACTIVE'; $NeighborhoodCommunity38->slug = Str::uuid();$NeighborhoodCommunity38->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity38->save();
        $NeighborhoodCommunity39= new NeighborhoodCommunity(); $NeighborhoodCommunity39->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity39->name = 'NARANJO DULCE'; $NeighborhoodCommunity39 ->description='COMUNIDAD'; $NeighborhoodCommunity39->type = 'COMUNIDAD'; $NeighborhoodCommunity39->state = 'ACTIVE'; $NeighborhoodCommunity39->slug = Str::uuid();$NeighborhoodCommunity39->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity39->save();
        $NeighborhoodCommunity40= new NeighborhoodCommunity(); $NeighborhoodCommunity40->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity40->name = 'SANTA ROSA'; $NeighborhoodCommunity40 ->description='COMUNIDAD'; $NeighborhoodCommunity40->type = 'COMUNIDAD'; $NeighborhoodCommunity40->state = 'ACTIVE'; $NeighborhoodCommunity40->slug = Str::uuid();$NeighborhoodCommunity40->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity40->save();
        $NeighborhoodCommunity41= new NeighborhoodCommunity(); $NeighborhoodCommunity41->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity41->name = 'VILLA NUEVA'; $NeighborhoodCommunity41 ->description='COMUNIDAD'; $NeighborhoodCommunity41->type = 'COMUNIDAD'; $NeighborhoodCommunity41->state = 'ACTIVE'; $NeighborhoodCommunity41->slug = Str::uuid();$NeighborhoodCommunity41->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity41->save();
        $NeighborhoodCommunity42= new NeighborhoodCommunity(); $NeighborhoodCommunity42->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity42->name = 'QUEBRADA CHICA'; $NeighborhoodCommunity42 ->description='COMUNIDAD'; $NeighborhoodCommunity42->type = 'COMUNIDAD'; $NeighborhoodCommunity42->state = 'ACTIVE'; $NeighborhoodCommunity42->slug = Str::uuid();$NeighborhoodCommunity42->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity42->save();
        $NeighborhoodCommunity43= new NeighborhoodCommunity(); $NeighborhoodCommunity43->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity43->name = 'SAN LUIS EL ANTA'; $NeighborhoodCommunity43 ->description='COMUNIDAD'; $NeighborhoodCommunity43->type = 'COMUNIDAD'; $NeighborhoodCommunity43->state = 'ACTIVE'; $NeighborhoodCommunity43->slug = Str::uuid();$NeighborhoodCommunity43->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity43->save();
        $NeighborhoodCommunity44= new NeighborhoodCommunity(); $NeighborhoodCommunity44->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity44->name = 'ALTO CALAMA'; $NeighborhoodCommunity44 ->description='COMUNIDAD'; $NeighborhoodCommunity44->type = 'COMUNIDAD'; $NeighborhoodCommunity44->state = 'ACTIVE'; $NeighborhoodCommunity44->slug = Str::uuid();$NeighborhoodCommunity44->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity44->save();
        $NeighborhoodCommunity45= new NeighborhoodCommunity(); $NeighborhoodCommunity45->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity45->name = 'ARROZALES'; $NeighborhoodCommunity45 ->description='COMUNIDAD'; $NeighborhoodCommunity45->type = 'COMUNIDAD'; $NeighborhoodCommunity45->state = 'ACTIVE'; $NeighborhoodCommunity45->slug = Str::uuid();$NeighborhoodCommunity45->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity45->save();
        $NeighborhoodCommunity46= new NeighborhoodCommunity(); $NeighborhoodCommunity46->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity46->name = 'BARREDERO'; $NeighborhoodCommunity46 ->description='COMUNIDAD'; $NeighborhoodCommunity46->type = 'COMUNIDAD'; $NeighborhoodCommunity46->state = 'ACTIVE'; $NeighborhoodCommunity46->slug = Str::uuid();$NeighborhoodCommunity46->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity46->save();
        $NeighborhoodCommunity47= new NeighborhoodCommunity(); $NeighborhoodCommunity47->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity47->name = 'CAÑADON BUENA VISTA'; $NeighborhoodCommunity47 ->description='COMUNIDAD'; $NeighborhoodCommunity47->type = 'COMUNIDAD'; $NeighborhoodCommunity47->state = 'ACTIVE'; $NeighborhoodCommunity47->slug = Str::uuid();$NeighborhoodCommunity47->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity47->save();
        $NeighborhoodCommunity48= new NeighborhoodCommunity(); $NeighborhoodCommunity48->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity48->name = 'COLONIA LINARES'; $NeighborhoodCommunity48 ->description='COMUNIDAD'; $NeighborhoodCommunity48->type = 'COMUNIDAD'; $NeighborhoodCommunity48->state = 'ACTIVE'; $NeighborhoodCommunity48->slug = Str::uuid();$NeighborhoodCommunity48->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity48->save();
        $NeighborhoodCommunity49= new NeighborhoodCommunity(); $NeighborhoodCommunity49->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity49->name = 'CAMPO GRANDE'; $NeighborhoodCommunity49 ->description='COMUNIDAD'; $NeighborhoodCommunity49->type = 'COMUNIDAD'; $NeighborhoodCommunity49->state = 'ACTIVE'; $NeighborhoodCommunity49->slug = Str::uuid();$NeighborhoodCommunity49->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity49->save();
        $NeighborhoodCommunity50= new NeighborhoodCommunity(); $NeighborhoodCommunity50->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity50->name = 'LA TALITA'; $NeighborhoodCommunity50 ->description='COMUNIDAD'; $NeighborhoodCommunity50->type = 'COMUNIDAD'; $NeighborhoodCommunity50->state = 'ACTIVE'; $NeighborhoodCommunity50->slug = Str::uuid();$NeighborhoodCommunity50->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity50->save();
        $NeighborhoodCommunity51= new NeighborhoodCommunity(); $NeighborhoodCommunity51->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity51->name = 'NARANJITOS'; $NeighborhoodCommunity51 ->description='COMUNIDAD'; $NeighborhoodCommunity51->type = 'COMUNIDAD'; $NeighborhoodCommunity51->state = 'ACTIVE'; $NeighborhoodCommunity51->slug = Str::uuid();$NeighborhoodCommunity51->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity51->save();
        $NeighborhoodCommunity52= new NeighborhoodCommunity(); $NeighborhoodCommunity52->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity52->name = 'PORCELANA'; $NeighborhoodCommunity52 ->description='COMUNIDAD'; $NeighborhoodCommunity52->type = 'COMUNIDAD'; $NeighborhoodCommunity52->state = 'ACTIVE'; $NeighborhoodCommunity52->slug = Str::uuid();$NeighborhoodCommunity52->subgovernment_code = 'bf4d54a5-ce78-467f-9764-b0271ea46e6f'; $NeighborhoodCommunity52->save();


    }
}
