<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Profession;
use Illuminate\Support\Str;

class ProfessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Profession1= new Profession(); $Profession1->name = 'ACADÉMICO'; $Profession1->description = ''; $Profession1->state = 'ACTIVE'; $Profession1->slug = Str::uuid(); $Profession1->save();
        $Profession2= new Profession(); $Profession2->name = 'ADJUNTO'; $Profession2->description = ''; $Profession2->state = 'ACTIVE'; $Profession2->slug = Str::uuid(); $Profession2->save();
        $Profession3= new Profession(); $Profession3->name = 'ADMINISTRACIÓN DE EMPRESAS'; $Profession3->description = ''; $Profession3->state = 'ACTIVE'; $Profession3->slug = Str::uuid(); $Profession3->save();
        $Profession4= new Profession(); $Profession4->name = 'ADMINISTRADOR'; $Profession4->description = ''; $Profession4->state = 'ACTIVE'; $Profession4->slug = Str::uuid(); $Profession4->save();
        $Profession5= new Profession(); $Profession5->name = 'ADMINISTRATIVO'; $Profession5->description = ''; $Profession5->state = 'ACTIVE'; $Profession5->slug = Str::uuid(); $Profession5->save();
        $Profession6= new Profession(); $Profession6->name = 'AGRICULTOR'; $Profession6->description = ''; $Profession6->state = 'ACTIVE'; $Profession6->slug = Str::uuid(); $Profession6->save();
        $Profession7= new Profession(); $Profession7->name = 'AGRÓNOMO'; $Profession7->description = ''; $Profession7->state = 'ACTIVE'; $Profession7->slug = Str::uuid(); $Profession7->save();
        $Profession8= new Profession(); $Profession8->name = 'ALARIFE'; $Profession8->description = ''; $Profession8->state = 'ACTIVE'; $Profession8->slug = Str::uuid(); $Profession8->save();
        $Profession9= new Profession(); $Profession9->name = 'ALBAÑIL'; $Profession9->description = ''; $Profession9->state = 'ACTIVE'; $Profession9->slug = Str::uuid(); $Profession9->save();
        $Profession10= new Profession(); $Profession10->name = 'ALERGÓLOGA'; $Profession10->description = ''; $Profession10->state = 'ACTIVE'; $Profession10->slug = Str::uuid(); $Profession10->save();
        $Profession11= new Profession(); $Profession11->name = 'ALERGÓLOGO'; $Profession11->description = ''; $Profession11->state = 'ACTIVE'; $Profession11->slug = Str::uuid(); $Profession11->save();
        $Profession12= new Profession(); $Profession12->name = 'ALFARERO'; $Profession12->description = ''; $Profession12->state = 'ACTIVE'; $Profession12->slug = Str::uuid(); $Profession12->save();
        $Profession13= new Profession(); $Profession13->name = 'ALMACENERA'; $Profession13->description = ''; $Profession13->state = 'ACTIVE'; $Profession13->slug = Str::uuid(); $Profession13->save();
        $Profession14= new Profession(); $Profession14->name = 'ALMACENERO'; $Profession14->description = ''; $Profession14->state = 'ACTIVE'; $Profession14->slug = Str::uuid(); $Profession14->save();
        $Profession15= new Profession(); $Profession15->name = 'AMA DE CASA'; $Profession15->description = ''; $Profession15->state = 'ACTIVE'; $Profession15->slug = Str::uuid(); $Profession15->save();
        $Profession16= new Profession(); $Profession16->name = 'ANATOMISTA'; $Profession16->description = ''; $Profession16->state = 'ACTIVE'; $Profession16->slug = Str::uuid(); $Profession16->save();
        $Profession17= new Profession(); $Profession17->name = 'ANESTESIÓLOGA'; $Profession17->description = ''; $Profession17->state = 'ACTIVE'; $Profession17->slug = Str::uuid(); $Profession17->save();
        $Profession18= new Profession(); $Profession18->name = 'ANESTESIÓLOGO'; $Profession18->description = ''; $Profession18->state = 'ACTIVE'; $Profession18->slug = Str::uuid(); $Profession18->save();
        $Profession19= new Profession(); $Profession19->name = 'ANTOLOGISTA'; $Profession19->description = ''; $Profession19->state = 'ACTIVE'; $Profession19->slug = Str::uuid(); $Profession19->save();
        $Profession20= new Profession(); $Profession20->name = 'ANTROPÓLOGO'; $Profession20->description = ''; $Profession20->state = 'ACTIVE'; $Profession20->slug = Str::uuid(); $Profession20->save();
        $Profession21= new Profession(); $Profession21->name = 'APICULTOR'; $Profession21->description = ''; $Profession21->state = 'ACTIVE'; $Profession21->slug = Str::uuid(); $Profession21->save();
        $Profession22= new Profession(); $Profession22->name = 'ARABISTA'; $Profession22->description = ''; $Profession22->state = 'ACTIVE'; $Profession22->slug = Str::uuid(); $Profession22->save();
        $Profession23= new Profession(); $Profession23->name = 'ARCHIVERO'; $Profession23->description = ''; $Profession23->state = 'ACTIVE'; $Profession23->slug = Str::uuid(); $Profession23->save();
        $Profession24= new Profession(); $Profession24->name = 'ARQUEÓLOGO'; $Profession24->description = ''; $Profession24->state = 'ACTIVE'; $Profession24->slug = Str::uuid(); $Profession24->save();
        $Profession25= new Profession(); $Profession25->name = 'ARQUITECTO'; $Profession25->description = ''; $Profession25->state = 'ACTIVE'; $Profession25->slug = Str::uuid(); $Profession25->save();
        $Profession26= new Profession(); $Profession26->name = 'ARTESANO'; $Profession26->description = ''; $Profession26->state = 'ACTIVE'; $Profession26->slug = Str::uuid(); $Profession26->save();
        $Profession27= new Profession(); $Profession27->name = 'ARTISTA'; $Profession27->description = ''; $Profession27->state = 'ACTIVE'; $Profession27->slug = Str::uuid(); $Profession27->save();
        $Profession28= new Profession(); $Profession28->name = 'ARTISTA PLASTICO'; $Profession28->description = ''; $Profession28->state = 'ACTIVE'; $Profession28->slug = Str::uuid(); $Profession28->save();
        $Profession29= new Profession(); $Profession29->name = 'ASESOR'; $Profession29->description = ''; $Profession29->state = 'ACTIVE'; $Profession29->slug = Str::uuid(); $Profession29->save();
        $Profession30= new Profession(); $Profession30->name = 'ASISTENTE'; $Profession30->description = ''; $Profession30->state = 'ACTIVE'; $Profession30->slug = Str::uuid(); $Profession30->save();
        $Profession31= new Profession(); $Profession31->name = 'ASTROFÍSICO'; $Profession31->description = ''; $Profession31->state = 'ACTIVE'; $Profession31->slug = Str::uuid(); $Profession31->save();
        $Profession32= new Profession(); $Profession32->name = 'ASTRÓLOGO'; $Profession32->description = ''; $Profession32->state = 'ACTIVE'; $Profession32->slug = Str::uuid(); $Profession32->save();
        $Profession33= new Profession(); $Profession33->name = 'ASTRÓNOMO'; $Profession33->description = ''; $Profession33->state = 'ACTIVE'; $Profession33->slug = Str::uuid(); $Profession33->save();
        $Profession34= new Profession(); $Profession34->name = 'ATLETA'; $Profession34->description = ''; $Profession34->state = 'ACTIVE'; $Profession34->slug = Str::uuid(); $Profession34->save();
        $Profession35= new Profession(); $Profession35->name = 'ATS'; $Profession35->description = ''; $Profession35->state = 'ACTIVE'; $Profession35->slug = Str::uuid(); $Profession35->save();
        $Profession36= new Profession(); $Profession36->name = 'AUDITOR'; $Profession36->description = ''; $Profession36->state = 'ACTIVE'; $Profession36->slug = Str::uuid(); $Profession36->save();
        $Profession37= new Profession(); $Profession37->name = 'AUTOR'; $Profession37->description = ''; $Profession37->state = 'ACTIVE'; $Profession37->slug = Str::uuid(); $Profession37->save();
        $Profession38= new Profession(); $Profession38->name = 'AUX CONTABLE'; $Profession38->description = ''; $Profession38->state = 'ACTIVE'; $Profession38->slug = Str::uuid(); $Profession38->save();
        $Profession39= new Profession(); $Profession39->name = 'AUXILIAR'; $Profession39->description = ''; $Profession39->state = 'ACTIVE'; $Profession39->slug = Str::uuid(); $Profession39->save();
        $Profession40= new Profession(); $Profession40->name = 'AUXILIAR DE ENFERMERIA'; $Profession40->description = ''; $Profession40->state = 'ACTIVE'; $Profession40->slug = Str::uuid(); $Profession40->save();
        $Profession41= new Profession(); $Profession41->name = 'AVIADOR MILITAR'; $Profession41->description = ''; $Profession41->state = 'ACTIVE'; $Profession41->slug = Str::uuid(); $Profession41->save();
        $Profession42= new Profession(); $Profession42->name = 'AVICULTOR'; $Profession42->description = ''; $Profession42->state = 'ACTIVE'; $Profession42->slug = Str::uuid(); $Profession42->save();
        $Profession43= new Profession(); $Profession43->name = 'AYUDANTE DE COCINA'; $Profession43->description = ''; $Profession43->state = 'ACTIVE'; $Profession43->slug = Str::uuid(); $Profession43->save();
        $Profession44= new Profession(); $Profession44->name = 'AYUDANTE SOLDADOR'; $Profession44->description = ''; $Profession44->state = 'ACTIVE'; $Profession44->slug = Str::uuid(); $Profession44->save();
        $Profession45= new Profession(); $Profession45->name = 'BACTERIÓLOGO'; $Profession45->description = ''; $Profession45->state = 'ACTIVE'; $Profession45->slug = Str::uuid(); $Profession45->save();
        $Profession46= new Profession(); $Profession46->name = 'BEDEL'; $Profession46->description = ''; $Profession46->state = 'ACTIVE'; $Profession46->slug = Str::uuid(); $Profession46->save();
        $Profession47= new Profession(); $Profession47->name = 'BIBLIÓGRAFO'; $Profession47->description = ''; $Profession47->state = 'ACTIVE'; $Profession47->slug = Str::uuid(); $Profession47->save();
        $Profession48= new Profession(); $Profession48->name = 'BIBLIOTECARIO'; $Profession48->description = ''; $Profession48->state = 'ACTIVE'; $Profession48->slug = Str::uuid(); $Profession48->save();
        $Profession49= new Profession(); $Profession49->name = 'BIOFÍSICO'; $Profession49->description = ''; $Profession49->state = 'ACTIVE'; $Profession49->slug = Str::uuid(); $Profession49->save();
        $Profession50= new Profession(); $Profession50->name = 'BIÓGRAFO'; $Profession50->description = ''; $Profession50->state = 'ACTIVE'; $Profession50->slug = Str::uuid(); $Profession50->save();
        $Profession51= new Profession(); $Profession51->name = 'BIÓLOGO'; $Profession51->description = ''; $Profession51->state = 'ACTIVE'; $Profession51->slug = Str::uuid(); $Profession51->save();
        $Profession52= new Profession(); $Profession52->name = 'BIOQUÍMICO'; $Profession52->description = ''; $Profession52->state = 'ACTIVE'; $Profession52->slug = Str::uuid(); $Profession52->save();
        $Profession53= new Profession(); $Profession53->name = 'BIOTECNOLOGO(A)'; $Profession53->description = ''; $Profession53->state = 'ACTIVE'; $Profession53->slug = Str::uuid(); $Profession53->save();
        $Profession54= new Profession(); $Profession54->name = 'BORDADORA'; $Profession54->description = ''; $Profession54->state = 'ACTIVE'; $Profession54->slug = Str::uuid(); $Profession54->save();
        $Profession55= new Profession(); $Profession55->name = 'BOTÁNICO'; $Profession55->description = ''; $Profession55->state = 'ACTIVE'; $Profession55->slug = Str::uuid(); $Profession55->save();
        $Profession56= new Profession(); $Profession56->name = 'CANCERÓLOGO'; $Profession56->description = ''; $Profession56->state = 'ACTIVE'; $Profession56->slug = Str::uuid(); $Profession56->save();
        $Profession57= new Profession(); $Profession57->name = 'CARDIÓLOGO'; $Profession57->description = ''; $Profession57->state = 'ACTIVE'; $Profession57->slug = Str::uuid(); $Profession57->save();
        $Profession58= new Profession(); $Profession58->name = 'CARNICERO'; $Profession58->description = ''; $Profession58->state = 'ACTIVE'; $Profession58->slug = Str::uuid(); $Profession58->save();
        $Profession59= new Profession(); $Profession59->name = 'CARPINTERO'; $Profession59->description = ''; $Profession59->state = 'ACTIVE'; $Profession59->slug = Str::uuid(); $Profession59->save();
        $Profession60= new Profession(); $Profession60->name = 'CARTÓGRAFO'; $Profession60->description = ''; $Profession60->state = 'ACTIVE'; $Profession60->slug = Str::uuid(); $Profession60->save();
        $Profession61= new Profession(); $Profession61->name = 'CASTRADOR'; $Profession61->description = ''; $Profession61->state = 'ACTIVE'; $Profession61->slug = Str::uuid(); $Profession61->save();
        $Profession62= new Profession(); $Profession62->name = 'CATEDRÁTICO'; $Profession62->description = ''; $Profession62->state = 'ACTIVE'; $Profession62->slug = Str::uuid(); $Profession62->save();
        $Profession63= new Profession(); $Profession63->name = 'CHAPISTA'; $Profession63->description = ''; $Profession63->state = 'ACTIVE'; $Profession63->slug = Str::uuid(); $Profession63->save();
        $Profession64= new Profession(); $Profession64->name = 'CHEF'; $Profession64->description = ''; $Profession64->state = 'ACTIVE'; $Profession64->slug = Str::uuid(); $Profession64->save();
        $Profession65= new Profession(); $Profession65->name = 'CHOFER'; $Profession65->description = ''; $Profession65->state = 'ACTIVE'; $Profession65->slug = Str::uuid(); $Profession65->save();
        $Profession66= new Profession(); $Profession66->name = 'CINEMATÓGRAFO'; $Profession66->description = ''; $Profession66->state = 'ACTIVE'; $Profession66->slug = Str::uuid(); $Profession66->save();
        $Profession67= new Profession(); $Profession67->name = 'CIRUJANO'; $Profession67->description = ''; $Profession67->state = 'ACTIVE'; $Profession67->slug = Str::uuid(); $Profession67->save();
        $Profession68= new Profession(); $Profession68->name = 'CITÓLOGO'; $Profession68->description = ''; $Profession68->state = 'ACTIVE'; $Profession68->slug = Str::uuid(); $Profession68->save();
        $Profession69= new Profession(); $Profession69->name = 'CLIMATÓLOGO'; $Profession69->description = ''; $Profession69->state = 'ACTIVE'; $Profession69->slug = Str::uuid(); $Profession69->save();
        $Profession70= new Profession(); $Profession70->name = 'COCINERO(A)'; $Profession70->description = ''; $Profession70->state = 'ACTIVE'; $Profession70->slug = Str::uuid(); $Profession70->save();
        $Profession71= new Profession(); $Profession71->name = 'CODIRECTOR'; $Profession71->description = ''; $Profession71->state = 'ACTIVE'; $Profession71->slug = Str::uuid(); $Profession71->save();
        $Profession72= new Profession(); $Profession72->name = 'COMADRÓN'; $Profession72->description = ''; $Profession72->state = 'ACTIVE'; $Profession72->slug = Str::uuid(); $Profession72->save();
        $Profession73= new Profession(); $Profession73->name = 'COMERCIANTE'; $Profession73->description = ''; $Profession73->state = 'ACTIVE'; $Profession73->slug = Str::uuid(); $Profession73->save();
        $Profession74= new Profession(); $Profession74->name = 'CONFECCIONISTA'; $Profession74->description = ''; $Profession74->state = 'ACTIVE'; $Profession74->slug = Str::uuid(); $Profession74->save();
        $Profession75= new Profession(); $Profession75->name = 'CONSEJERO'; $Profession75->description = ''; $Profession75->state = 'ACTIVE'; $Profession75->slug = Str::uuid(); $Profession75->save();
        $Profession76= new Profession(); $Profession76->name = 'CONSERJE'; $Profession76->description = ''; $Profession76->state = 'ACTIVE'; $Profession76->slug = Str::uuid(); $Profession76->save();
        $Profession77= new Profession(); $Profession77->name = 'CONSERVADOR'; $Profession77->description = ''; $Profession77->state = 'ACTIVE'; $Profession77->slug = Str::uuid(); $Profession77->save();
        $Profession78= new Profession(); $Profession78->name = 'CONSTRUCTOR'; $Profession78->description = ''; $Profession78->state = 'ACTIVE'; $Profession78->slug = Str::uuid(); $Profession78->save();
        $Profession79= new Profession(); $Profession79->name = 'CONSULTOR'; $Profession79->description = ''; $Profession79->state = 'ACTIVE'; $Profession79->slug = Str::uuid(); $Profession79->save();
        $Profession80= new Profession(); $Profession80->name = 'CONTADOR(A) GENERAL'; $Profession80->description = ''; $Profession80->state = 'ACTIVE'; $Profession80->slug = Str::uuid(); $Profession80->save();
        $Profession81= new Profession(); $Profession81->name = 'CONTRATISTA'; $Profession81->description = ''; $Profession81->state = 'ACTIVE'; $Profession81->slug = Str::uuid(); $Profession81->save();
        $Profession82= new Profession(); $Profession82->name = 'CONTROLADOR DE TRANSITO AEREO'; $Profession82->description = ''; $Profession82->state = 'ACTIVE'; $Profession82->slug = Str::uuid(); $Profession82->save();
        $Profession83= new Profession(); $Profession83->name = 'COORDINADOR'; $Profession83->description = ''; $Profession83->state = 'ACTIVE'; $Profession83->slug = Str::uuid(); $Profession83->save();
        $Profession84= new Profession(); $Profession84->name = 'COSMETOLGA'; $Profession84->description = ''; $Profession84->state = 'ACTIVE'; $Profession84->slug = Str::uuid(); $Profession84->save();
        $Profession85= new Profession(); $Profession85->name = 'COSMÓGRAFO'; $Profession85->description = ''; $Profession85->state = 'ACTIVE'; $Profession85->slug = Str::uuid(); $Profession85->save();
        $Profession86= new Profession(); $Profession86->name = 'COSMÓLOGO'; $Profession86->description = ''; $Profession86->state = 'ACTIVE'; $Profession86->slug = Str::uuid(); $Profession86->save();
        $Profession87= new Profession(); $Profession87->name = 'COSTURERA'; $Profession87->description = ''; $Profession87->state = 'ACTIVE'; $Profession87->slug = Str::uuid(); $Profession87->save();
        $Profession88= new Profession(); $Profession88->name = 'CRIMINALISTA'; $Profession88->description = ''; $Profession88->state = 'ACTIVE'; $Profession88->slug = Str::uuid(); $Profession88->save();
        $Profession89= new Profession(); $Profession89->name = 'CRONÓLOGO'; $Profession89->description = ''; $Profession89->state = 'ACTIVE'; $Profession89->slug = Str::uuid(); $Profession89->save();
        $Profession90= new Profession(); $Profession90->name = 'DACTILOGRAFIA'; $Profession90->description = ''; $Profession90->state = 'ACTIVE'; $Profession90->slug = Str::uuid(); $Profession90->save();
        $Profession91= new Profession(); $Profession91->name = 'DECANO'; $Profession91->description = ''; $Profession91->state = 'ACTIVE'; $Profession91->slug = Str::uuid(); $Profession91->save();
        $Profession92= new Profession(); $Profession92->name = 'DECORADOR'; $Profession92->description = ''; $Profession92->state = 'ACTIVE'; $Profession92->slug = Str::uuid(); $Profession92->save();
        $Profession93= new Profession(); $Profession93->name = 'DEFENSOR'; $Profession93->description = ''; $Profession93->state = 'ACTIVE'; $Profession93->slug = Str::uuid(); $Profession93->save();
        $Profession94= new Profession(); $Profession94->name = 'DELEGADO'; $Profession94->description = ''; $Profession94->state = 'ACTIVE'; $Profession94->slug = Str::uuid(); $Profession94->save();
        $Profession95= new Profession(); $Profession95->name = 'DELINEANTE'; $Profession95->description = ''; $Profession95->state = 'ACTIVE'; $Profession95->slug = Str::uuid(); $Profession95->save();
        $Profession96= new Profession(); $Profession96->name = 'DEMÓGRAFO'; $Profession96->description = ''; $Profession96->state = 'ACTIVE'; $Profession96->slug = Str::uuid(); $Profession96->save();
        $Profession97= new Profession(); $Profession97->name = 'DENTISTA'; $Profession97->description = ''; $Profession97->state = 'ACTIVE'; $Profession97->slug = Str::uuid(); $Profession97->save();
        $Profession98= new Profession(); $Profession98->name = 'DERMATÓLOGO'; $Profession98->description = ''; $Profession98->state = 'ACTIVE'; $Profession98->slug = Str::uuid(); $Profession98->save();
        $Profession99= new Profession(); $Profession99->name = 'DIBUJANTE'; $Profession99->description = ''; $Profession99->state = 'ACTIVE'; $Profession99->slug = Str::uuid(); $Profession99->save();
        $Profession100= new Profession(); $Profession100->name = 'DIRECTIVO'; $Profession100->description = ''; $Profession100->state = 'ACTIVE'; $Profession100->slug = Str::uuid(); $Profession100->save();
        $Profession101= new Profession(); $Profession101->name = 'DIRECTOR'; $Profession101->description = ''; $Profession101->state = 'ACTIVE'; $Profession101->slug = Str::uuid(); $Profession101->save();
        $Profession102= new Profession(); $Profession102->name = 'DIRIGENTE'; $Profession102->description = ''; $Profession102->state = 'ACTIVE'; $Profession102->slug = Str::uuid(); $Profession102->save();
        $Profession103= new Profession(); $Profession103->name = 'DISCAPACITADO(A)'; $Profession103->description = ''; $Profession103->state = 'ACTIVE'; $Profession103->slug = Str::uuid(); $Profession103->save();
        $Profession104= new Profession(); $Profession104->name = 'DOCTOR'; $Profession104->description = ''; $Profession104->state = 'ACTIVE'; $Profession104->slug = Str::uuid(); $Profession104->save();
        $Profession105= new Profession(); $Profession105->name = 'DOCUMENTALISTA'; $Profession105->description = ''; $Profession105->state = 'ACTIVE'; $Profession105->slug = Str::uuid(); $Profession105->save();
        $Profession106= new Profession(); $Profession106->name = 'ECÓLOGO'; $Profession106->description = ''; $Profession106->state = 'ACTIVE'; $Profession106->slug = Str::uuid(); $Profession106->save();
        $Profession107= new Profession(); $Profession107->name = 'ECONOMISTA'; $Profession107->description = ''; $Profession107->state = 'ACTIVE'; $Profession107->slug = Str::uuid(); $Profession107->save();
        $Profession108= new Profession(); $Profession108->name = 'EDUCADOR'; $Profession108->description = ''; $Profession108->state = 'ACTIVE'; $Profession108->slug = Str::uuid(); $Profession108->save();
        $Profession109= new Profession(); $Profession109->name = 'EGIPTÓLOGO'; $Profession109->description = ''; $Profession109->state = 'ACTIVE'; $Profession109->slug = Str::uuid(); $Profession109->save();
        $Profession110= new Profession(); $Profession110->name = 'EGRRESADO DE DERECHO'; $Profession110->description = ''; $Profession110->state = 'ACTIVE'; $Profession110->slug = Str::uuid(); $Profession110->save();
        $Profession111= new Profession(); $Profession111->name = 'ELECTRICISTA'; $Profession111->description = ''; $Profession111->state = 'ACTIVE'; $Profession111->slug = Str::uuid(); $Profession111->save();
        $Profession112= new Profession(); $Profession112->name = 'EMPLEADA PUBLICO'; $Profession112->description = ''; $Profession112->state = 'ACTIVE'; $Profession112->slug = Str::uuid(); $Profession112->save();
        $Profession113= new Profession(); $Profession113->name = 'EMPLEADO'; $Profession113->description = ''; $Profession113->state = 'ACTIVE'; $Profession113->slug = Str::uuid(); $Profession113->save();
        $Profession114= new Profession(); $Profession114->name = 'EMPLEADO PRIVADO'; $Profession114->description = ''; $Profession114->state = 'ACTIVE'; $Profession114->slug = Str::uuid(); $Profession114->save();
        $Profession115= new Profession(); $Profession115->name = 'EMPLEADO PUBLICO'; $Profession115->description = ''; $Profession115->state = 'ACTIVE'; $Profession115->slug = Str::uuid(); $Profession115->save();
        $Profession116= new Profession(); $Profession116->name = 'EMPRESARIO'; $Profession116->description = ''; $Profession116->state = 'ACTIVE'; $Profession116->slug = Str::uuid(); $Profession116->save();
        $Profession117= new Profession(); $Profession117->name = 'ENCUADERNADORA'; $Profession117->description = ''; $Profession117->state = 'ACTIVE'; $Profession117->slug = Str::uuid(); $Profession117->save();
        $Profession118= new Profession(); $Profession118->name = 'ENDOCRINÓLOGO'; $Profession118->description = ''; $Profession118->state = 'ACTIVE'; $Profession118->slug = Str::uuid(); $Profession118->save();
        $Profession119= new Profession(); $Profession119->name = 'ENFERMERA'; $Profession119->description = ''; $Profession119->state = 'ACTIVE'; $Profession119->slug = Str::uuid(); $Profession119->save();
        $Profession120= new Profession(); $Profession120->name = 'ENFERMERO'; $Profession120->description = ''; $Profession120->state = 'ACTIVE'; $Profession120->slug = Str::uuid(); $Profession120->save();
        $Profession121= new Profession(); $Profession121->name = 'ENÓLOGO'; $Profession121->description = ''; $Profession121->state = 'ACTIVE'; $Profession121->slug = Str::uuid(); $Profession121->save();
        $Profession122= new Profession(); $Profession122->name = 'ENTOMÓLOGO'; $Profession122->description = ''; $Profession122->state = 'ACTIVE'; $Profession122->slug = Str::uuid(); $Profession122->save();
        $Profession123= new Profession(); $Profession123->name = 'EPIDEMIÓLOGO'; $Profession123->description = ''; $Profession123->state = 'ACTIVE'; $Profession123->slug = Str::uuid(); $Profession123->save();
        $Profession124= new Profession(); $Profession124->name = 'ESCRITOR'; $Profession124->description = ''; $Profession124->state = 'ACTIVE'; $Profession124->slug = Str::uuid(); $Profession124->save();
        $Profession125= new Profession(); $Profession125->name = 'ESPECIALISTA'; $Profession125->description = ''; $Profession125->state = 'ACTIVE'; $Profession125->slug = Str::uuid(); $Profession125->save();
        $Profession126= new Profession(); $Profession126->name = 'ESPELEÓLOGO'; $Profession126->description = ''; $Profession126->state = 'ACTIVE'; $Profession126->slug = Str::uuid(); $Profession126->save();
        $Profession127= new Profession(); $Profession127->name = 'ESTADISTA'; $Profession127->description = ''; $Profession127->state = 'ACTIVE'; $Profession127->slug = Str::uuid(); $Profession127->save();
        $Profession128= new Profession(); $Profession128->name = 'ESTADÍSTICO'; $Profession128->description = ''; $Profession128->state = 'ACTIVE'; $Profession128->slug = Str::uuid(); $Profession128->save();
        $Profession129= new Profession(); $Profession129->name = 'ESTUDIANTE'; $Profession129->description = ''; $Profession129->state = 'ACTIVE'; $Profession129->slug = Str::uuid(); $Profession129->save();
        $Profession130= new Profession(); $Profession130->name = 'ETIMÓLOGA'; $Profession130->description = ''; $Profession130->state = 'ACTIVE'; $Profession130->slug = Str::uuid(); $Profession130->save();
        $Profession131= new Profession(); $Profession131->name = 'ETIMÓLOGO'; $Profession131->description = ''; $Profession131->state = 'ACTIVE'; $Profession131->slug = Str::uuid(); $Profession131->save();
        $Profession132= new Profession(); $Profession132->name = 'ETNÓGRAFO'; $Profession132->description = ''; $Profession132->state = 'ACTIVE'; $Profession132->slug = Str::uuid(); $Profession132->save();
        $Profession133= new Profession(); $Profession133->name = 'ETNÓLOGO'; $Profession133->description = ''; $Profession133->state = 'ACTIVE'; $Profession133->slug = Str::uuid(); $Profession133->save();
        $Profession134= new Profession(); $Profession134->name = 'ETÓLOGO'; $Profession134->description = ''; $Profession134->state = 'ACTIVE'; $Profession134->slug = Str::uuid(); $Profession134->save();
        $Profession135= new Profession(); $Profession135->name = 'EXAMINADOR'; $Profession135->description = ''; $Profession135->state = 'ACTIVE'; $Profession135->slug = Str::uuid(); $Profession135->save();
        $Profession136= new Profession(); $Profession136->name = 'EXPERTA EN BELLEZA'; $Profession136->description = ''; $Profession136->state = 'ACTIVE'; $Profession136->slug = Str::uuid(); $Profession136->save();
        $Profession137= new Profession(); $Profession137->name = 'EXTRANJERO'; $Profession137->description = ''; $Profession137->state = 'ACTIVE'; $Profession137->slug = Str::uuid(); $Profession137->save();
        $Profession138= new Profession(); $Profession138->name = 'FACULTATIVO'; $Profession138->description = ''; $Profession138->state = 'ACTIVE'; $Profession138->slug = Str::uuid(); $Profession138->save();
        $Profession139= new Profession(); $Profession139->name = 'FARMACÉUTICO'; $Profession139->description = ''; $Profession139->state = 'ACTIVE'; $Profession139->slug = Str::uuid(); $Profession139->save();
        $Profession140= new Profession(); $Profession140->name = 'FARMACÓLOGO'; $Profession140->description = ''; $Profession140->state = 'ACTIVE'; $Profession140->slug = Str::uuid(); $Profession140->save();
        $Profession141= new Profession(); $Profession141->name = 'FILÓLOGO'; $Profession141->description = ''; $Profession141->state = 'ACTIVE'; $Profession141->slug = Str::uuid(); $Profession141->save();
        $Profession142= new Profession(); $Profession142->name = 'FILÓSOFO'; $Profession142->description = ''; $Profession142->state = 'ACTIVE'; $Profession142->slug = Str::uuid(); $Profession142->save();
        $Profession143= new Profession(); $Profession143->name = 'FISCAL'; $Profession143->description = ''; $Profession143->state = 'ACTIVE'; $Profession143->slug = Str::uuid(); $Profession143->save();
        $Profession144= new Profession(); $Profession144->name = 'FÍSICO'; $Profession144->description = ''; $Profession144->state = 'ACTIVE'; $Profession144->slug = Str::uuid(); $Profession144->save();
        $Profession145= new Profession(); $Profession145->name = 'FISIÓLOGO'; $Profession145->description = ''; $Profession145->state = 'ACTIVE'; $Profession145->slug = Str::uuid(); $Profession145->save();
        $Profession146= new Profession(); $Profession146->name = 'FISIOTERAPEUTA'; $Profession146->description = ''; $Profession146->state = 'ACTIVE'; $Profession146->slug = Str::uuid(); $Profession146->save();
        $Profession147= new Profession(); $Profession147->name = 'FONETISTA'; $Profession147->description = ''; $Profession147->state = 'ACTIVE'; $Profession147->slug = Str::uuid(); $Profession147->save();
        $Profession148= new Profession(); $Profession148->name = 'FONÍATRA'; $Profession148->description = ''; $Profession148->state = 'ACTIVE'; $Profession148->slug = Str::uuid(); $Profession148->save();
        $Profession149= new Profession(); $Profession149->name = 'FONÓLOGO'; $Profession149->description = ''; $Profession149->state = 'ACTIVE'; $Profession149->slug = Str::uuid(); $Profession149->save();
        $Profession150= new Profession(); $Profession150->name = 'FORENSE'; $Profession150->description = ''; $Profession150->state = 'ACTIVE'; $Profession150->slug = Str::uuid(); $Profession150->save();
        $Profession151= new Profession(); $Profession151->name = 'FOTÓGRAFO'; $Profession151->description = ''; $Profession151->state = 'ACTIVE'; $Profession151->slug = Str::uuid(); $Profession151->save();
        $Profession152= new Profession(); $Profession152->name = 'FRUTICULTOR'; $Profession152->description = ''; $Profession152->state = 'ACTIVE'; $Profession152->slug = Str::uuid(); $Profession152->save();
        $Profession153= new Profession(); $Profession153->name = 'FUNCIONARIO'; $Profession153->description = ''; $Profession153->state = 'ACTIVE'; $Profession153->slug = Str::uuid(); $Profession153->save();
        $Profession154= new Profession(); $Profession154->name = 'FUNDIDOR'; $Profession154->description = ''; $Profession154->state = 'ACTIVE'; $Profession154->slug = Str::uuid(); $Profession154->save();
        $Profession155= new Profession(); $Profession155->name = 'GANADERO'; $Profession155->description = ''; $Profession155->state = 'ACTIVE'; $Profession155->slug = Str::uuid(); $Profession155->save();
        $Profession156= new Profession(); $Profession156->name = 'GASTRONOMO'; $Profession156->description = ''; $Profession156->state = 'ACTIVE'; $Profession156->slug = Str::uuid(); $Profession156->save();
        $Profession157= new Profession(); $Profession157->name = 'GEMÓLOGO'; $Profession157->description = ''; $Profession157->state = 'ACTIVE'; $Profession157->slug = Str::uuid(); $Profession157->save();
        $Profession158= new Profession(); $Profession158->name = 'GENETISTA'; $Profession158->description = ''; $Profession158->state = 'ACTIVE'; $Profession158->slug = Str::uuid(); $Profession158->save();
        $Profession159= new Profession(); $Profession159->name = 'GEOBOTÁNICA'; $Profession159->description = ''; $Profession159->state = 'ACTIVE'; $Profession159->slug = Str::uuid(); $Profession159->save();
        $Profession160= new Profession(); $Profession160->name = 'GEODESTA'; $Profession160->description = ''; $Profession160->state = 'ACTIVE'; $Profession160->slug = Str::uuid(); $Profession160->save();
        $Profession161= new Profession(); $Profession161->name = 'GEOFÍSICO'; $Profession161->description = ''; $Profession161->state = 'ACTIVE'; $Profession161->slug = Str::uuid(); $Profession161->save();
        $Profession162= new Profession(); $Profession162->name = 'GEÓGRAFO'; $Profession162->description = ''; $Profession162->state = 'ACTIVE'; $Profession162->slug = Str::uuid(); $Profession162->save();
        $Profession163= new Profession(); $Profession163->name = 'GEÓLOGO'; $Profession163->description = ''; $Profession163->state = 'ACTIVE'; $Profession163->slug = Str::uuid(); $Profession163->save();
        $Profession164= new Profession(); $Profession164->name = 'GEOMÁNTICO'; $Profession164->description = ''; $Profession164->state = 'ACTIVE'; $Profession164->slug = Str::uuid(); $Profession164->save();
        $Profession165= new Profession(); $Profession165->name = 'GEÓMETRA'; $Profession165->description = ''; $Profession165->state = 'ACTIVE'; $Profession165->slug = Str::uuid(); $Profession165->save();
        $Profession166= new Profession(); $Profession166->name = 'GEOQUÍMICA'; $Profession166->description = ''; $Profession166->state = 'ACTIVE'; $Profession166->slug = Str::uuid(); $Profession166->save();
        $Profession167= new Profession(); $Profession167->name = 'GERENTE'; $Profession167->description = ''; $Profession167->state = 'ACTIVE'; $Profession167->slug = Str::uuid(); $Profession167->save();
        $Profession168= new Profession(); $Profession168->name = 'GERIATRA'; $Profession168->description = ''; $Profession168->state = 'ACTIVE'; $Profession168->slug = Str::uuid(); $Profession168->save();
        $Profession169= new Profession(); $Profession169->name = 'GERONTÓLOGO'; $Profession169->description = ''; $Profession169->state = 'ACTIVE'; $Profession169->slug = Str::uuid(); $Profession169->save();
        $Profession170= new Profession(); $Profession170->name = 'GESTOR'; $Profession170->description = ''; $Profession170->state = 'ACTIVE'; $Profession170->slug = Str::uuid(); $Profession170->save();
        $Profession171= new Profession(); $Profession171->name = 'GRABADOR'; $Profession171->description = ''; $Profession171->state = 'ACTIVE'; $Profession171->slug = Str::uuid(); $Profession171->save();
        $Profession172= new Profession(); $Profession172->name = 'GRADUADO SOCIAL'; $Profession172->description = ''; $Profession172->state = 'ACTIVE'; $Profession172->slug = Str::uuid(); $Profession172->save();
        $Profession173= new Profession(); $Profession173->name = 'GRAFICO'; $Profession173->description = ''; $Profession173->state = 'ACTIVE'; $Profession173->slug = Str::uuid(); $Profession173->save();
        $Profession174= new Profession(); $Profession174->name = 'GRAFÓLOGO'; $Profession174->description = ''; $Profession174->state = 'ACTIVE'; $Profession174->slug = Str::uuid(); $Profession174->save();
        $Profession175= new Profession(); $Profession175->name = 'GRAMÁTICO'; $Profession175->description = ''; $Profession175->state = 'ACTIVE'; $Profession175->slug = Str::uuid(); $Profession175->save();
        $Profession176= new Profession(); $Profession176->name = 'HEMATÓLOGO'; $Profession176->description = ''; $Profession176->state = 'ACTIVE'; $Profession176->slug = Str::uuid(); $Profession176->save();
        $Profession177= new Profession(); $Profession177->name = 'HEPATÓLOGO'; $Profession177->description = ''; $Profession177->state = 'ACTIVE'; $Profession177->slug = Str::uuid(); $Profession177->save();
        $Profession178= new Profession(); $Profession178->name = 'HIDROGEÓLOGO'; $Profession178->description = ''; $Profession178->state = 'ACTIVE'; $Profession178->slug = Str::uuid(); $Profession178->save();
        $Profession179= new Profession(); $Profession179->name = 'HIDRÓGRAFO'; $Profession179->description = ''; $Profession179->state = 'ACTIVE'; $Profession179->slug = Str::uuid(); $Profession179->save();
        $Profession180= new Profession(); $Profession180->name = 'HIDRÓLOGO'; $Profession180->description = ''; $Profession180->state = 'ACTIVE'; $Profession180->slug = Str::uuid(); $Profession180->save();
        $Profession181= new Profession(); $Profession181->name = 'HIGIENISTA'; $Profession181->description = ''; $Profession181->state = 'ACTIVE'; $Profession181->slug = Str::uuid(); $Profession181->save();
        $Profession182= new Profession(); $Profession182->name = 'HISPANISTA'; $Profession182->description = ''; $Profession182->state = 'ACTIVE'; $Profession182->slug = Str::uuid(); $Profession182->save();
        $Profession183= new Profession(); $Profession183->name = 'HISTORIADOR'; $Profession183->description = ''; $Profession183->state = 'ACTIVE'; $Profession183->slug = Str::uuid(); $Profession183->save();
        $Profession184= new Profession(); $Profession184->name = 'HOMEÓPATA'; $Profession184->description = ''; $Profession184->state = 'ACTIVE'; $Profession184->slug = Str::uuid(); $Profession184->save();
        $Profession185= new Profession(); $Profession185->name = 'INDEPENDIENTE'; $Profession185->description = ''; $Profession185->state = 'ACTIVE'; $Profession185->slug = Str::uuid(); $Profession185->save();
        $Profession186= new Profession(); $Profession186->name = 'INFORMÁTICO'; $Profession186->description = ''; $Profession186->state = 'ACTIVE'; $Profession186->slug = Str::uuid(); $Profession186->save();
        $Profession187= new Profession(); $Profession187->name = 'ING. AGRONOMO'; $Profession187->description = ''; $Profession187->state = 'ACTIVE'; $Profession187->slug = Str::uuid(); $Profession187->save();
        $Profession188= new Profession(); $Profession188->name = 'ING. ALIMENTOS'; $Profession188->description = ''; $Profession188->state = 'ACTIVE'; $Profession188->slug = Str::uuid(); $Profession188->save();
        $Profession189= new Profession(); $Profession189->name = 'ING. CIVIL'; $Profession189->description = ''; $Profession189->state = 'ACTIVE'; $Profession189->slug = Str::uuid(); $Profession189->save();
        $Profession190= new Profession(); $Profession190->name = 'ING. COMERCIAL'; $Profession190->description = ''; $Profession190->state = 'ACTIVE'; $Profession190->slug = Str::uuid(); $Profession190->save();
        $Profession191= new Profession(); $Profession191->name = 'ING. ELECTRICO'; $Profession191->description = ''; $Profession191->state = 'ACTIVE'; $Profession191->slug = Str::uuid(); $Profession191->save();
        $Profession192= new Profession(); $Profession192->name = 'ING. ELECTRÓNICO'; $Profession192->description = ''; $Profession192->state = 'ACTIVE'; $Profession192->slug = Str::uuid(); $Profession192->save();
        $Profession193= new Profession(); $Profession193->name = 'ING. FORESTAL'; $Profession193->description = ''; $Profession193->state = 'ACTIVE'; $Profession193->slug = Str::uuid(); $Profession193->save();
        $Profession194= new Profession(); $Profession194->name = 'ING. GEOLOGO'; $Profession194->description = ''; $Profession194->state = 'ACTIVE'; $Profession194->slug = Str::uuid(); $Profession194->save();
        $Profession195= new Profession(); $Profession195->name = 'ING. INDUSTRIAL'; $Profession195->description = ''; $Profession195->state = 'ACTIVE'; $Profession195->slug = Str::uuid(); $Profession195->save();
        $Profession196= new Profession(); $Profession196->name = 'ING. QUÍMICO/CA'; $Profession196->description = ''; $Profession196->state = 'ACTIVE'; $Profession196->slug = Str::uuid(); $Profession196->save();
        $Profession197= new Profession(); $Profession197->name = 'INGENIERO'; $Profession197->description = ''; $Profession197->state = 'ACTIVE'; $Profession197->slug = Str::uuid(); $Profession197->save();
        $Profession198= new Profession(); $Profession198->name = 'INGENIERO TÉCNICO'; $Profession198->description = ''; $Profession198->state = 'ACTIVE'; $Profession198->slug = Str::uuid(); $Profession198->save();
        $Profession199= new Profession(); $Profession199->name = 'INMUNÓLOGO'; $Profession199->description = ''; $Profession199->state = 'ACTIVE'; $Profession199->slug = Str::uuid(); $Profession199->save();
        $Profession200= new Profession(); $Profession200->name = 'INSPECTOR'; $Profession200->description = ''; $Profession200->state = 'ACTIVE'; $Profession200->slug = Str::uuid(); $Profession200->save();
        $Profession201= new Profession(); $Profession201->name = 'INSTRUMENTADORA QUIRURGICA'; $Profession201->description = ''; $Profession201->state = 'ACTIVE'; $Profession201->slug = Str::uuid(); $Profession201->save();
        $Profession202= new Profession(); $Profession202->name = 'INTERINO'; $Profession202->description = ''; $Profession202->state = 'ACTIVE'; $Profession202->slug = Str::uuid(); $Profession202->save();
        $Profession203= new Profession(); $Profession203->name = 'INTERVENTOR'; $Profession203->description = ''; $Profession203->state = 'ACTIVE'; $Profession203->slug = Str::uuid(); $Profession203->save();
        $Profession204= new Profession(); $Profession204->name = 'INVESTIGADOR'; $Profession204->description = ''; $Profession204->state = 'ACTIVE'; $Profession204->slug = Str::uuid(); $Profession204->save();
        $Profession205= new Profession(); $Profession205->name = 'JARDINERO'; $Profession205->description = ''; $Profession205->state = 'ACTIVE'; $Profession205->slug = Str::uuid(); $Profession205->save();
        $Profession206= new Profession(); $Profession206->name = 'JEFE'; $Profession206->description = ''; $Profession206->state = 'ACTIVE'; $Profession206->slug = Str::uuid(); $Profession206->save();
        $Profession207= new Profession(); $Profession207->name = 'JOYERO'; $Profession207->description = ''; $Profession207->state = 'ACTIVE'; $Profession207->slug = Str::uuid(); $Profession207->save();
        $Profession208= new Profession(); $Profession208->name = 'JUBILADO'; $Profession208->description = ''; $Profession208->state = 'ACTIVE'; $Profession208->slug = Str::uuid(); $Profession208->save();
        $Profession209= new Profession(); $Profession209->name = 'JUEZ'; $Profession209->description = ''; $Profession209->state = 'ACTIVE'; $Profession209->slug = Str::uuid(); $Profession209->save();
        $Profession210= new Profession(); $Profession210->name = 'LABORATORISTA'; $Profession210->description = ''; $Profession210->state = 'ACTIVE'; $Profession210->slug = Str::uuid(); $Profession210->save();
        $Profession211= new Profession(); $Profession211->name = 'LABORES DE CASA'; $Profession211->description = ''; $Profession211->state = 'ACTIVE'; $Profession211->slug = Str::uuid(); $Profession211->save();
        $Profession212= new Profession(); $Profession212->name = 'LATINISTA'; $Profession212->description = ''; $Profession212->state = 'ACTIVE'; $Profession212->slug = Str::uuid(); $Profession212->save();
        $Profession213= new Profession(); $Profession213->name = 'LECTOR'; $Profession213->description = ''; $Profession213->state = 'ACTIVE'; $Profession213->slug = Str::uuid(); $Profession213->save();
        $Profession214= new Profession(); $Profession214->name = 'LETRADO (ABOGADO)'; $Profession214->description = ''; $Profession214->state = 'ACTIVE'; $Profession214->slug = Str::uuid(); $Profession214->save();
        $Profession215= new Profession(); $Profession215->name = 'LEXICÓGRAFO'; $Profession215->description = ''; $Profession215->state = 'ACTIVE'; $Profession215->slug = Str::uuid(); $Profession215->save();
        $Profession216= new Profession(); $Profession216->name = 'LEXICÓLOGO'; $Profession216->description = ''; $Profession216->state = 'ACTIVE'; $Profession216->slug = Str::uuid(); $Profession216->save();
        $Profession217= new Profession(); $Profession217->name = 'LIC EN TRABAJO SOCIAL'; $Profession217->description = ''; $Profession217->state = 'ACTIVE'; $Profession217->slug = Str::uuid(); $Profession217->save();
        $Profession218= new Profession(); $Profession218->name = 'LIC MESTRA DE COMUNICACION'; $Profession218->description = ''; $Profession218->state = 'ACTIVE'; $Profession218->slug = Str::uuid(); $Profession218->save();
        $Profession219= new Profession(); $Profession219->name = 'LICENCIADO'; $Profession219->description = ''; $Profession219->state = 'ACTIVE'; $Profession219->slug = Str::uuid(); $Profession219->save();
        $Profession220= new Profession(); $Profession220->name = 'LINGÜISTA'; $Profession220->description = ''; $Profession220->state = 'ACTIVE'; $Profession220->slug = Str::uuid(); $Profession220->save();
        $Profession221= new Profession(); $Profession221->name = 'LOCUTOR'; $Profession221->description = ''; $Profession221->state = 'ACTIVE'; $Profession221->slug = Str::uuid(); $Profession221->save();
        $Profession222= new Profession(); $Profession222->name = 'LOGOPEDA'; $Profession222->description = ''; $Profession222->state = 'ACTIVE'; $Profession222->slug = Str::uuid(); $Profession222->save();
        $Profession223= new Profession(); $Profession223->name = 'MAESTRO'; $Profession223->description = ''; $Profession223->state = 'ACTIVE'; $Profession223->slug = Str::uuid(); $Profession223->save();
        $Profession224= new Profession(); $Profession224->name = 'MASAJISTA'; $Profession224->description = ''; $Profession224->state = 'ACTIVE'; $Profession224->slug = Str::uuid(); $Profession224->save();
        $Profession225= new Profession(); $Profession225->name = 'MATARIFE'; $Profession225->description = ''; $Profession225->state = 'ACTIVE'; $Profession225->slug = Str::uuid(); $Profession225->save();
        $Profession226= new Profession(); $Profession226->name = 'MATEMÁTICO'; $Profession226->description = ''; $Profession226->state = 'ACTIVE'; $Profession226->slug = Str::uuid(); $Profession226->save();
        $Profession227= new Profession(); $Profession227->name = 'MATRÓN'; $Profession227->description = ''; $Profession227->state = 'ACTIVE'; $Profession227->slug = Str::uuid(); $Profession227->save();
        $Profession228= new Profession(); $Profession228->name = 'MECANICO'; $Profession228->description = ''; $Profession228->state = 'ACTIVE'; $Profession228->slug = Str::uuid(); $Profession228->save();
        $Profession229= new Profession(); $Profession229->name = 'MECANICO DENTAL'; $Profession229->description = ''; $Profession229->state = 'ACTIVE'; $Profession229->slug = Str::uuid(); $Profession229->save();
        $Profession230= new Profession(); $Profession230->name = 'MEDICO'; $Profession230->description = ''; $Profession230->state = 'ACTIVE'; $Profession230->slug = Str::uuid(); $Profession230->save();
        $Profession231= new Profession(); $Profession231->name = 'METALÚRGICO'; $Profession231->description = ''; $Profession231->state = 'ACTIVE'; $Profession231->slug = Str::uuid(); $Profession231->save();
        $Profession232= new Profession(); $Profession232->name = 'METEORÓLOGO'; $Profession232->description = ''; $Profession232->state = 'ACTIVE'; $Profession232->slug = Str::uuid(); $Profession232->save();
        $Profession233= new Profession(); $Profession233->name = 'MICÓLOGO'; $Profession233->description = ''; $Profession233->state = 'ACTIVE'; $Profession233->slug = Str::uuid(); $Profession233->save();
        $Profession234= new Profession(); $Profession234->name = 'MICROBIOLÓGICO'; $Profession234->description = ''; $Profession234->state = 'ACTIVE'; $Profession234->slug = Str::uuid(); $Profession234->save();
        $Profession235= new Profession(); $Profession235->name = 'MICROCIRUJANO'; $Profession235->description = ''; $Profession235->state = 'ACTIVE'; $Profession235->slug = Str::uuid(); $Profession235->save();
        $Profession236= new Profession(); $Profession236->name = 'MILITAR'; $Profession236->description = ''; $Profession236->state = 'ACTIVE'; $Profession236->slug = Str::uuid(); $Profession236->save();
        $Profession237= new Profession(); $Profession237->name = 'MIMÓGRAFO'; $Profession237->description = ''; $Profession237->state = 'ACTIVE'; $Profession237->slug = Str::uuid(); $Profession237->save();
        $Profession238= new Profession(); $Profession238->name = 'MINERALOGISTA'; $Profession238->description = ''; $Profession238->state = 'ACTIVE'; $Profession238->slug = Str::uuid(); $Profession238->save();
        $Profession239= new Profession(); $Profession239->name = 'MINERO'; $Profession239->description = ''; $Profession239->state = 'ACTIVE'; $Profession239->slug = Str::uuid(); $Profession239->save();
        $Profession240= new Profession(); $Profession240->name = 'MODISTA'; $Profession240->description = ''; $Profession240->state = 'ACTIVE'; $Profession240->slug = Str::uuid(); $Profession240->save();
        $Profession241= new Profession(); $Profession241->name = 'MONITOR'; $Profession241->description = ''; $Profession241->state = 'ACTIVE'; $Profession241->slug = Str::uuid(); $Profession241->save();
        $Profession242= new Profession(); $Profession242->name = 'MUSICO'; $Profession242->description = ''; $Profession242->state = 'ACTIVE'; $Profession242->slug = Str::uuid(); $Profession242->save();
        $Profession243= new Profession(); $Profession243->name = 'MUSICÓLOGO'; $Profession243->description = ''; $Profession243->state = 'ACTIVE'; $Profession243->slug = Str::uuid(); $Profession243->save();
        $Profession244= new Profession(); $Profession244->name = 'NATURISTA'; $Profession244->description = ''; $Profession244->state = 'ACTIVE'; $Profession244->slug = Str::uuid(); $Profession244->save();
        $Profession245= new Profession(); $Profession245->name = 'NATURÓPATA'; $Profession245->description = ''; $Profession245->state = 'ACTIVE'; $Profession245->slug = Str::uuid(); $Profession245->save();
        $Profession246= new Profession(); $Profession246->name = 'NEFRÓLOGO'; $Profession246->description = ''; $Profession246->state = 'ACTIVE'; $Profession246->slug = Str::uuid(); $Profession246->save();
        $Profession247= new Profession(); $Profession247->name = 'NEUMÓLOGO'; $Profession247->description = ''; $Profession247->state = 'ACTIVE'; $Profession247->slug = Str::uuid(); $Profession247->save();
        $Profession248= new Profession(); $Profession248->name = 'NEUROANATOMISTA'; $Profession248->description = ''; $Profession248->state = 'ACTIVE'; $Profession248->slug = Str::uuid(); $Profession248->save();
        $Profession249= new Profession(); $Profession249->name = 'NEUROBIÓLOGO'; $Profession249->description = ''; $Profession249->state = 'ACTIVE'; $Profession249->slug = Str::uuid(); $Profession249->save();
        $Profession250= new Profession(); $Profession250->name = 'NEUROCIRUJANO'; $Profession250->description = ''; $Profession250->state = 'ACTIVE'; $Profession250->slug = Str::uuid(); $Profession250->save();
        $Profession251= new Profession(); $Profession251->name = 'NEUROEMBRIÓLOGO'; $Profession251->description = ''; $Profession251->state = 'ACTIVE'; $Profession251->slug = Str::uuid(); $Profession251->save();
        $Profession252= new Profession(); $Profession252->name = 'NEUROFISIÓLOGO'; $Profession252->description = ''; $Profession252->state = 'ACTIVE'; $Profession252->slug = Str::uuid(); $Profession252->save();
        $Profession253= new Profession(); $Profession253->name = 'NEURÓLOGO'; $Profession253->description = ''; $Profession253->state = 'ACTIVE'; $Profession253->slug = Str::uuid(); $Profession253->save();
        $Profession254= new Profession(); $Profession254->name = 'NINGUNO'; $Profession254->description = ''; $Profession254->state = 'ACTIVE'; $Profession254->slug = Str::uuid(); $Profession254->save();
        $Profession255= new Profession(); $Profession255->name = 'NUTRÓLOGO'; $Profession255->description = ''; $Profession255->state = 'ACTIVE'; $Profession255->slug = Str::uuid(); $Profession255->save();
        $Profession256= new Profession(); $Profession256->name = 'OCEANÓGRAFO'; $Profession256->description = ''; $Profession256->state = 'ACTIVE'; $Profession256->slug = Str::uuid(); $Profession256->save();
        $Profession257= new Profession(); $Profession257->name = 'ODONTÓLOGO'; $Profession257->description = ''; $Profession257->state = 'ACTIVE'; $Profession257->slug = Str::uuid(); $Profession257->save();
        $Profession258= new Profession(); $Profession258->name = 'OFICIAL'; $Profession258->description = ''; $Profession258->state = 'ACTIVE'; $Profession258->slug = Str::uuid(); $Profession258->save();
        $Profession259= new Profession(); $Profession259->name = 'OFICINISTA'; $Profession259->description = ''; $Profession259->state = 'ACTIVE'; $Profession259->slug = Str::uuid(); $Profession259->save();
        $Profession260= new Profession(); $Profession260->name = 'OFTALMÓLOGO'; $Profession260->description = ''; $Profession260->state = 'ACTIVE'; $Profession260->slug = Str::uuid(); $Profession260->save();
        $Profession261= new Profession(); $Profession261->name = 'ONCÓLOGO'; $Profession261->description = ''; $Profession261->state = 'ACTIVE'; $Profession261->slug = Str::uuid(); $Profession261->save();
        $Profession262= new Profession(); $Profession262->name = 'OPERADOR DE EQUIPO PESADO'; $Profession262->description = ''; $Profession262->state = 'ACTIVE'; $Profession262->slug = Str::uuid(); $Profession262->save();
        $Profession263= new Profession(); $Profession263->name = 'ÓPTICO'; $Profession263->description = ''; $Profession263->state = 'ACTIVE'; $Profession263->slug = Str::uuid(); $Profession263->save();
        $Profession264= new Profession(); $Profession264->name = 'OPTOMETRISTA'; $Profession264->description = ''; $Profession264->state = 'ACTIVE'; $Profession264->slug = Str::uuid(); $Profession264->save();
        $Profession265= new Profession(); $Profession265->name = 'ORDENANZA'; $Profession265->description = ''; $Profession265->state = 'ACTIVE'; $Profession265->slug = Str::uuid(); $Profession265->save();
        $Profession266= new Profession(); $Profession266->name = 'ORFEBRE'; $Profession266->description = ''; $Profession266->state = 'ACTIVE'; $Profession266->slug = Str::uuid(); $Profession266->save();
        $Profession267= new Profession(); $Profession267->name = 'ORIENTADOR'; $Profession267->description = ''; $Profession267->state = 'ACTIVE'; $Profession267->slug = Str::uuid(); $Profession267->save();
        $Profession268= new Profession(); $Profession268->name = 'ORNITÓLOGO'; $Profession268->description = ''; $Profession268->state = 'ACTIVE'; $Profession268->slug = Str::uuid(); $Profession268->save();
        $Profession269= new Profession(); $Profession269->name = 'ORTOPÉDICO'; $Profession269->description = ''; $Profession269->state = 'ACTIVE'; $Profession269->slug = Str::uuid(); $Profession269->save();
        $Profession270= new Profession(); $Profession270->name = 'ORTOPEDISTA'; $Profession270->description = ''; $Profession270->state = 'ACTIVE'; $Profession270->slug = Str::uuid(); $Profession270->save();
        $Profession271= new Profession(); $Profession271->name = 'OSTEÓLOGO'; $Profession271->description = ''; $Profession271->state = 'ACTIVE'; $Profession271->slug = Str::uuid(); $Profession271->save();
        $Profession272= new Profession(); $Profession272->name = 'OSTEÓPATA'; $Profession272->description = ''; $Profession272->state = 'ACTIVE'; $Profession272->slug = Str::uuid(); $Profession272->save();
        $Profession273= new Profession(); $Profession273->name = 'OTORRINOLARINGÓLOGO'; $Profession273->description = ''; $Profession273->state = 'ACTIVE'; $Profession273->slug = Str::uuid(); $Profession273->save();
        $Profession274= new Profession(); $Profession274->name = 'OTRO'; $Profession274->description = ''; $Profession274->state = 'ACTIVE'; $Profession274->slug = Str::uuid(); $Profession274->save();
        $Profession275= new Profession(); $Profession275->name = 'PALEOBIÓLOGO'; $Profession275->description = ''; $Profession275->state = 'ACTIVE'; $Profession275->slug = Str::uuid(); $Profession275->save();
        $Profession276= new Profession(); $Profession276->name = 'PALEOBOTÁNICO'; $Profession276->description = ''; $Profession276->state = 'ACTIVE'; $Profession276->slug = Str::uuid(); $Profession276->save();
        $Profession277= new Profession(); $Profession277->name = 'PALEÓGRAFO'; $Profession277->description = ''; $Profession277->state = 'ACTIVE'; $Profession277->slug = Str::uuid(); $Profession277->save();
        $Profession278= new Profession(); $Profession278->name = 'PALEÓLOGO'; $Profession278->description = ''; $Profession278->state = 'ACTIVE'; $Profession278->slug = Str::uuid(); $Profession278->save();
        $Profession279= new Profession(); $Profession279->name = 'PALEONTÓLOGO'; $Profession279->description = ''; $Profession279->state = 'ACTIVE'; $Profession279->slug = Str::uuid(); $Profession279->save();
        $Profession280= new Profession(); $Profession280->name = 'PANADERO'; $Profession280->description = ''; $Profession280->state = 'ACTIVE'; $Profession280->slug = Str::uuid(); $Profession280->save();
        $Profession281= new Profession(); $Profession281->name = 'PANIFICADOR'; $Profession281->description = ''; $Profession281->state = 'ACTIVE'; $Profession281->slug = Str::uuid(); $Profession281->save();
        $Profession282= new Profession(); $Profession282->name = 'PASTOR'; $Profession282->description = ''; $Profession282->state = 'ACTIVE'; $Profession282->slug = Str::uuid(); $Profession282->save();
        $Profession283= new Profession(); $Profession283->name = 'PATÓLOGO'; $Profession283->description = ''; $Profession283->state = 'ACTIVE'; $Profession283->slug = Str::uuid(); $Profession283->save();
        $Profession284= new Profession(); $Profession284->name = 'PEDAGOGO'; $Profession284->description = ''; $Profession284->state = 'ACTIVE'; $Profession284->slug = Str::uuid(); $Profession284->save();
        $Profession285= new Profession(); $Profession285->name = 'PEDIATRA'; $Profession285->description = ''; $Profession285->state = 'ACTIVE'; $Profession285->slug = Str::uuid(); $Profession285->save();
        $Profession286= new Profession(); $Profession286->name = 'PEDICURO'; $Profession286->description = ''; $Profession286->state = 'ACTIVE'; $Profession286->slug = Str::uuid(); $Profession286->save();
        $Profession287= new Profession(); $Profession287->name = 'PEINADORA'; $Profession287->description = ''; $Profession287->state = 'ACTIVE'; $Profession287->slug = Str::uuid(); $Profession287->save();
        $Profession288= new Profession(); $Profession288->name = 'PELUQUERA'; $Profession288->description = ''; $Profession288->state = 'ACTIVE'; $Profession288->slug = Str::uuid(); $Profession288->save();
        $Profession289= new Profession(); $Profession289->name = 'PELUQUERIA'; $Profession289->description = ''; $Profession289->state = 'ACTIVE'; $Profession289->slug = Str::uuid(); $Profession289->save();
        $Profession290= new Profession(); $Profession290->name = 'PERIODISTA'; $Profession290->description = ''; $Profession290->state = 'ACTIVE'; $Profession290->slug = Str::uuid(); $Profession290->save();
        $Profession291= new Profession(); $Profession291->name = 'PERITO'; $Profession291->description = ''; $Profession291->state = 'ACTIVE'; $Profession291->slug = Str::uuid(); $Profession291->save();
        $Profession292= new Profession(); $Profession292->name = 'PINTOR'; $Profession292->description = ''; $Profession292->state = 'ACTIVE'; $Profession292->slug = Str::uuid(); $Profession292->save();
        $Profession293= new Profession(); $Profession293->name = 'PISCICULTOR'; $Profession293->description = ''; $Profession293->state = 'ACTIVE'; $Profession293->slug = Str::uuid(); $Profession293->save();
        $Profession294= new Profession(); $Profession294->name = 'PLOMERO'; $Profession294->description = ''; $Profession294->state = 'ACTIVE'; $Profession294->slug = Str::uuid(); $Profession294->save();
        $Profession295= new Profession(); $Profession295->name = 'PLOMERO GASISTA'; $Profession295->description = ''; $Profession295->state = 'ACTIVE'; $Profession295->slug = Str::uuid(); $Profession295->save();
        $Profession296= new Profession(); $Profession296->name = 'PODÓLOGO'; $Profession296->description = ''; $Profession296->state = 'ACTIVE'; $Profession296->slug = Str::uuid(); $Profession296->save();
        $Profession297= new Profession(); $Profession297->name = 'POLICIA'; $Profession297->description = ''; $Profession297->state = 'ACTIVE'; $Profession297->slug = Str::uuid(); $Profession297->save();
        $Profession298= new Profession(); $Profession298->name = 'PORTERO'; $Profession298->description = ''; $Profession298->state = 'ACTIVE'; $Profession298->slug = Str::uuid(); $Profession298->save();
        $Profession299= new Profession(); $Profession299->name = 'PREHISTORIADOR'; $Profession299->description = ''; $Profession299->state = 'ACTIVE'; $Profession299->slug = Str::uuid(); $Profession299->save();
        $Profession300= new Profession(); $Profession300->name = 'PRESIDENTE'; $Profession300->description = ''; $Profession300->state = 'ACTIVE'; $Profession300->slug = Str::uuid(); $Profession300->save();
        $Profession301= new Profession(); $Profession301->name = 'PROCTÓLOGO'; $Profession301->description = ''; $Profession301->state = 'ACTIVE'; $Profession301->slug = Str::uuid(); $Profession301->save();
        $Profession302= new Profession(); $Profession302->name = 'PROFESOR'; $Profession302->description = ''; $Profession302->state = 'ACTIVE'; $Profession302->slug = Str::uuid(); $Profession302->save();
        $Profession303= new Profession(); $Profession303->name = 'PROGRAMADOR'; $Profession303->description = ''; $Profession303->state = 'ACTIVE'; $Profession303->slug = Str::uuid(); $Profession303->save();
        $Profession304= new Profession(); $Profession304->name = 'PROGRAMADOR COMERCIAL'; $Profession304->description = ''; $Profession304->state = 'ACTIVE'; $Profession304->slug = Str::uuid(); $Profession304->save();
        $Profession305= new Profession(); $Profession305->name = 'PROMOTORA DE VENTAS'; $Profession305->description = ''; $Profession305->state = 'ACTIVE'; $Profession305->slug = Str::uuid(); $Profession305->save();
        $Profession306= new Profession(); $Profession306->name = 'PROTÉSICO'; $Profession306->description = ''; $Profession306->state = 'ACTIVE'; $Profession306->slug = Str::uuid(); $Profession306->save();
        $Profession307= new Profession(); $Profession307->name = 'PROVEEDOR'; $Profession307->description = ''; $Profession307->state = 'ACTIVE'; $Profession307->slug = Str::uuid(); $Profession307->save();
        $Profession308= new Profession(); $Profession308->name = 'PSICOANALISTA'; $Profession308->description = ''; $Profession308->state = 'ACTIVE'; $Profession308->slug = Str::uuid(); $Profession308->save();
        $Profession309= new Profession(); $Profession309->name = 'PSICOFÍSICO'; $Profession309->description = ''; $Profession309->state = 'ACTIVE'; $Profession309->slug = Str::uuid(); $Profession309->save();
        $Profession310= new Profession(); $Profession310->name = 'PSICÓLOGO'; $Profession310->description = ''; $Profession310->state = 'ACTIVE'; $Profession310->slug = Str::uuid(); $Profession310->save();
        $Profession311= new Profession(); $Profession311->name = 'PSICOPEDAGOGO'; $Profession311->description = ''; $Profession311->state = 'ACTIVE'; $Profession311->slug = Str::uuid(); $Profession311->save();
        $Profession312= new Profession(); $Profession312->name = 'PSICOTERAPEUTA'; $Profession312->description = ''; $Profession312->state = 'ACTIVE'; $Profession312->slug = Str::uuid(); $Profession312->save();
        $Profession313= new Profession(); $Profession313->name = 'PSIQUIATRA'; $Profession313->description = ''; $Profession313->state = 'ACTIVE'; $Profession313->slug = Str::uuid(); $Profession313->save();
        $Profession314= new Profession(); $Profession314->name = 'PUBLICISTA'; $Profession314->description = ''; $Profession314->state = 'ACTIVE'; $Profession314->slug = Str::uuid(); $Profession314->save();
        $Profession315= new Profession(); $Profession315->name = 'PUBLICITARIO'; $Profession315->description = ''; $Profession315->state = 'ACTIVE'; $Profession315->slug = Str::uuid(); $Profession315->save();
        $Profession316= new Profession(); $Profession316->name = 'PUERICULTOR'; $Profession316->description = ''; $Profession316->state = 'ACTIVE'; $Profession316->slug = Str::uuid(); $Profession316->save();
        $Profession317= new Profession(); $Profession317->name = 'QUÍMICO'; $Profession317->description = ''; $Profession317->state = 'ACTIVE'; $Profession317->slug = Str::uuid(); $Profession317->save();
        $Profession318= new Profession(); $Profession318->name = 'QUIROPRÁCTICO'; $Profession318->description = ''; $Profession318->state = 'ACTIVE'; $Profession318->slug = Str::uuid(); $Profession318->save();
        $Profession319= new Profession(); $Profession319->name = 'RADIOASTRÓNOMO'; $Profession319->description = ''; $Profession319->state = 'ACTIVE'; $Profession319->slug = Str::uuid(); $Profession319->save();
        $Profession320= new Profession(); $Profession320->name = 'RADIOFONISTA'; $Profession320->description = ''; $Profession320->state = 'ACTIVE'; $Profession320->slug = Str::uuid(); $Profession320->save();
        $Profession321= new Profession(); $Profession321->name = 'RADIÓLOGO'; $Profession321->description = ''; $Profession321->state = 'ACTIVE'; $Profession321->slug = Str::uuid(); $Profession321->save();
        $Profession322= new Profession(); $Profession322->name = 'RADIOTÉCNICO'; $Profession322->description = ''; $Profession322->state = 'ACTIVE'; $Profession322->slug = Str::uuid(); $Profession322->save();
        $Profession323= new Profession(); $Profession323->name = 'RADIOTELEFONISTA'; $Profession323->description = ''; $Profession323->state = 'ACTIVE'; $Profession323->slug = Str::uuid(); $Profession323->save();
        $Profession324= new Profession(); $Profession324->name = 'RADIOTELEGRAFISTA'; $Profession324->description = ''; $Profession324->state = 'ACTIVE'; $Profession324->slug = Str::uuid(); $Profession324->save();
        $Profession325= new Profession(); $Profession325->name = 'RADIOTERAPEUTA'; $Profession325->description = ''; $Profession325->state = 'ACTIVE'; $Profession325->slug = Str::uuid(); $Profession325->save();
        $Profession326= new Profession(); $Profession326->name = 'RECTOR'; $Profession326->description = ''; $Profession326->state = 'ACTIVE'; $Profession326->slug = Str::uuid(); $Profession326->save();
        $Profession327= new Profession(); $Profession327->name = 'RELIGIOSA'; $Profession327->description = ''; $Profession327->state = 'ACTIVE'; $Profession327->slug = Str::uuid(); $Profession327->save();
        $Profession328= new Profession(); $Profession328->name = 'RELOJERO'; $Profession328->description = ''; $Profession328->state = 'ACTIVE'; $Profession328->slug = Str::uuid(); $Profession328->save();
        $Profession329= new Profession(); $Profession329->name = 'RENTISTA'; $Profession329->description = ''; $Profession329->state = 'ACTIVE'; $Profession329->slug = Str::uuid(); $Profession329->save();
        $Profession330= new Profession(); $Profession330->name = 'REPORTERA'; $Profession330->description = ''; $Profession330->state = 'ACTIVE'; $Profession330->slug = Str::uuid(); $Profession330->save();
        $Profession331= new Profession(); $Profession331->name = 'REPOSTERA'; $Profession331->description = ''; $Profession331->state = 'ACTIVE'; $Profession331->slug = Str::uuid(); $Profession331->save();
        $Profession332= new Profession(); $Profession332->name = 'SACERDOTE'; $Profession332->description = ''; $Profession332->state = 'ACTIVE'; $Profession332->slug = Str::uuid(); $Profession332->save();
        $Profession333= new Profession(); $Profession333->name = 'SALTEÑERO'; $Profession333->description = ''; $Profession333->state = 'ACTIVE'; $Profession333->slug = Str::uuid(); $Profession333->save();
        $Profession334= new Profession(); $Profession334->name = 'SANITARIO'; $Profession334->description = ''; $Profession334->state = 'ACTIVE'; $Profession334->slug = Str::uuid(); $Profession334->save();
        $Profession335= new Profession(); $Profession335->name = 'SASTRE'; $Profession335->description = ''; $Profession335->state = 'ACTIVE'; $Profession335->slug = Str::uuid(); $Profession335->save();
        $Profession336= new Profession(); $Profession336->name = 'SECRETARIA'; $Profession336->description = ''; $Profession336->state = 'ACTIVE'; $Profession336->slug = Str::uuid(); $Profession336->save();
        $Profession337= new Profession(); $Profession337->name = 'SECRETARIA COMERCIAL'; $Profession337->description = ''; $Profession337->state = 'ACTIVE'; $Profession337->slug = Str::uuid(); $Profession337->save();
        $Profession338= new Profession(); $Profession338->name = 'SECRETARIO'; $Profession338->description = ''; $Profession338->state = 'ACTIVE'; $Profession338->slug = Str::uuid(); $Profession338->save();
        $Profession339= new Profession(); $Profession339->name = 'SERENO'; $Profession339->description = ''; $Profession339->state = 'ACTIVE'; $Profession339->slug = Str::uuid(); $Profession339->save();
        $Profession340= new Profession(); $Profession340->name = 'SEXÓLOGO'; $Profession340->description = ''; $Profession340->state = 'ACTIVE'; $Profession340->slug = Str::uuid(); $Profession340->save();
        $Profession341= new Profession(); $Profession341->name = 'SISMÓLOGO'; $Profession341->description = ''; $Profession341->state = 'ACTIVE'; $Profession341->slug = Str::uuid(); $Profession341->save();
        $Profession342= new Profession(); $Profession342->name = 'SOCIÓLOGO'; $Profession342->description = ''; $Profession342->state = 'ACTIVE'; $Profession342->slug = Str::uuid(); $Profession342->save();
        $Profession343= new Profession(); $Profession343->name = 'SOLDADOR'; $Profession343->description = ''; $Profession343->state = 'ACTIVE'; $Profession343->slug = Str::uuid(); $Profession343->save();
        $Profession344= new Profession(); $Profession344->name = 'SUBDELEGADO'; $Profession344->description = ''; $Profession344->state = 'ACTIVE'; $Profession344->slug = Str::uuid(); $Profession344->save();
        $Profession345= new Profession(); $Profession345->name = 'SUBDIRECTOR'; $Profession345->description = ''; $Profession345->state = 'ACTIVE'; $Profession345->slug = Str::uuid(); $Profession345->save();
        $Profession346= new Profession(); $Profession346->name = 'SUBSECRETARIO'; $Profession346->description = ''; $Profession346->state = 'ACTIVE'; $Profession346->slug = Str::uuid(); $Profession346->save();
        $Profession347= new Profession(); $Profession347->name = 'TAPICERO'; $Profession347->description = ''; $Profession347->state = 'ACTIVE'; $Profession347->slug = Str::uuid(); $Profession347->save();
        $Profession348= new Profession(); $Profession348->name = 'TEC. ELECTROMECANICO'; $Profession348->description = ''; $Profession348->state = 'ACTIVE'; $Profession348->slug = Str::uuid(); $Profession348->save();
        $Profession349= new Profession(); $Profession349->name = 'TEC EN ALIMENTACION'; $Profession349->description = ''; $Profession349->state = 'ACTIVE'; $Profession349->slug = Str::uuid(); $Profession349->save();
        $Profession350= new Profession(); $Profession350->name = 'TEC EN APLICACIONES'; $Profession350->description = ''; $Profession350->state = 'ACTIVE'; $Profession350->slug = Str::uuid(); $Profession350->save();
        $Profession351= new Profession(); $Profession351->name = 'TEC EN AVIACIONES'; $Profession351->description = ''; $Profession351->state = 'ACTIVE'; $Profession351->slug = Str::uuid(); $Profession351->save();
        $Profession352= new Profession(); $Profession352->name = 'TEC. EN ELECTRONICA'; $Profession352->description = ''; $Profession352->state = 'ACTIVE'; $Profession352->slug = Str::uuid(); $Profession352->save();
        $Profession353= new Profession(); $Profession353->name = 'TEC. HIDRICO'; $Profession353->description = ''; $Profession353->state = 'ACTIVE'; $Profession353->slug = Str::uuid(); $Profession353->save();
        $Profession354= new Profession(); $Profession354->name = 'TEC. INDUSTRIAL'; $Profession354->description = ''; $Profession354->state = 'ACTIVE'; $Profession354->slug = Str::uuid(); $Profession354->save();
        $Profession355= new Profession(); $Profession355->name = 'TEC INSTALADOR DE GAS'; $Profession355->description = ''; $Profession355->state = 'ACTIVE'; $Profession355->slug = Str::uuid(); $Profession355->save();
        $Profession356= new Profession(); $Profession356->name = 'TEC. MECÁNICO'; $Profession356->description = ''; $Profession356->state = 'ACTIVE'; $Profession356->slug = Str::uuid(); $Profession356->save();
        $Profession357= new Profession(); $Profession357->name = 'TEC. OPERADOR DE COMPUTADORA'; $Profession357->description = ''; $Profession357->state = 'ACTIVE'; $Profession357->slug = Str::uuid(); $Profession357->save();
        $Profession358= new Profession(); $Profession358->name = 'TÉCNICO'; $Profession358->description = ''; $Profession358->state = 'ACTIVE'; $Profession358->slug = Str::uuid(); $Profession358->save();
        $Profession359= new Profession(); $Profession359->name = 'TECNICO BANCARIO'; $Profession359->description = ''; $Profession359->state = 'ACTIVE'; $Profession359->slug = Str::uuid(); $Profession359->save();
        $Profession360= new Profession(); $Profession360->name = 'TECNICO EN MANEJOS DE PAQUETES'; $Profession360->description = ''; $Profession360->state = 'ACTIVE'; $Profession360->slug = Str::uuid(); $Profession360->save();
        $Profession361= new Profession(); $Profession361->name = 'TECNICO SUP. AERONAUTICO'; $Profession361->description = ''; $Profession361->state = 'ACTIVE'; $Profession361->slug = Str::uuid(); $Profession361->save();
        $Profession362= new Profession(); $Profession362->name = 'TELEFONISTA'; $Profession362->description = ''; $Profession362->state = 'ACTIVE'; $Profession362->slug = Str::uuid(); $Profession362->save();
        $Profession363= new Profession(); $Profession363->name = 'TEÓLOGO'; $Profession363->description = ''; $Profession363->state = 'ACTIVE'; $Profession363->slug = Str::uuid(); $Profession363->save();
        $Profession364= new Profession(); $Profession364->name = 'TERAPEUTA'; $Profession364->description = ''; $Profession364->state = 'ACTIVE'; $Profession364->slug = Str::uuid(); $Profession364->save();
        $Profession365= new Profession(); $Profession365->name = 'TOCOGINECÓLOGO'; $Profession365->description = ''; $Profession365->state = 'ACTIVE'; $Profession365->slug = Str::uuid(); $Profession365->save();
        $Profession366= new Profession(); $Profession366->name = 'TOCÓLOGO'; $Profession366->description = ''; $Profession366->state = 'ACTIVE'; $Profession366->slug = Str::uuid(); $Profession366->save();
        $Profession367= new Profession(); $Profession367->name = 'TOPOGRAFO'; $Profession367->description = ''; $Profession367->state = 'ACTIVE'; $Profession367->slug = Str::uuid(); $Profession367->save();
        $Profession368= new Profession(); $Profession368->name = 'TORNERO'; $Profession368->description = ''; $Profession368->state = 'ACTIVE'; $Profession368->slug = Str::uuid(); $Profession368->save();
        $Profession369= new Profession(); $Profession369->name = 'TOXICÓLOGO'; $Profession369->description = ''; $Profession369->state = 'ACTIVE'; $Profession369->slug = Str::uuid(); $Profession369->save();
        $Profession370= new Profession(); $Profession370->name = 'TRACTORISTA'; $Profession370->description = ''; $Profession370->state = 'ACTIVE'; $Profession370->slug = Str::uuid(); $Profession370->save();
        $Profession371= new Profession(); $Profession371->name = 'TRADUCTOR'; $Profession371->description = ''; $Profession371->state = 'ACTIVE'; $Profession371->slug = Str::uuid(); $Profession371->save();
        $Profession372= new Profession(); $Profession372->name = 'TRANSCRIPTOR'; $Profession372->description = ''; $Profession372->state = 'ACTIVE'; $Profession372->slug = Str::uuid(); $Profession372->save();
        $Profession373= new Profession(); $Profession373->name = 'TRANSPORTISTA'; $Profession373->description = ''; $Profession373->state = 'ACTIVE'; $Profession373->slug = Str::uuid(); $Profession373->save();
        $Profession374= new Profession(); $Profession374->name = 'TRAUMATÓLOGO'; $Profession374->description = ''; $Profession374->state = 'ACTIVE'; $Profession374->slug = Str::uuid(); $Profession374->save();
        $Profession375= new Profession(); $Profession375->name = 'TUTOR'; $Profession375->description = ''; $Profession375->state = 'ACTIVE'; $Profession375->slug = Str::uuid(); $Profession375->save();
        $Profession376= new Profession(); $Profession376->name = 'URÓLOGO'; $Profession376->description = ''; $Profession376->state = 'ACTIVE'; $Profession376->slug = Str::uuid(); $Profession376->save();
        $Profession377= new Profession(); $Profession377->name = 'VETERINARIO'; $Profession377->description = ''; $Profession377->state = 'ACTIVE'; $Profession377->slug = Str::uuid(); $Profession377->save();
        $Profession378= new Profession(); $Profession378->name = 'VICEDECANO'; $Profession378->description = ''; $Profession378->state = 'ACTIVE'; $Profession378->slug = Str::uuid(); $Profession378->save();
        $Profession379= new Profession(); $Profession379->name = 'VICEDIRECTOR'; $Profession379->description = ''; $Profession379->state = 'ACTIVE'; $Profession379->slug = Str::uuid(); $Profession379->save();
        $Profession380= new Profession(); $Profession380->name = 'VICEGERENTE'; $Profession380->description = ''; $Profession380->state = 'ACTIVE'; $Profession380->slug = Str::uuid(); $Profession380->save();
        $Profession381= new Profession(); $Profession381->name = 'VICEPRESIDENTE'; $Profession381->description = ''; $Profession381->state = 'ACTIVE'; $Profession381->slug = Str::uuid(); $Profession381->save();
        $Profession382= new Profession(); $Profession382->name = 'VICERRECTOR'; $Profession382->description = ''; $Profession382->state = 'ACTIVE'; $Profession382->slug = Str::uuid(); $Profession382->save();
        $Profession383= new Profession(); $Profession383->name = 'VICESECRETARIO'; $Profession383->description = ''; $Profession383->state = 'ACTIVE'; $Profession383->slug = Str::uuid(); $Profession383->save();
        $Profession384= new Profession(); $Profession384->name = 'VIRÓLOGO'; $Profession384->description = ''; $Profession384->state = 'ACTIVE'; $Profession384->slug = Str::uuid(); $Profession384->save();
        $Profession385= new Profession(); $Profession385->name = 'VISITADOR MEDICO'; $Profession385->description = ''; $Profession385->state = 'ACTIVE'; $Profession385->slug = Str::uuid(); $Profession385->save();
        $Profession386= new Profession(); $Profession386->name = 'VITICULTOR'; $Profession386->description = ''; $Profession386->state = 'ACTIVE'; $Profession386->slug = Str::uuid(); $Profession386->save();
        $Profession387= new Profession(); $Profession387->name = 'VULCANÓLOGO'; $Profession387->description = ''; $Profession387->state = 'ACTIVE'; $Profession387->slug = Str::uuid(); $Profession387->save();
        $Profession388= new Profession(); $Profession388->name = 'XILÓGRAFO'; $Profession388->description = ''; $Profession388->state = 'ACTIVE'; $Profession388->slug = Str::uuid(); $Profession388->save();
        $Profession389= new Profession(); $Profession389->name = 'ZAPATERO'; $Profession389->description = ''; $Profession389->state = 'ACTIVE'; $Profession389->slug = Str::uuid(); $Profession389->save();
        $Profession390= new Profession(); $Profession390->name = 'ZOÓLOGO'; $Profession390->description = ''; $Profession390->state = 'ACTIVE'; $Profession390->slug = Str::uuid(); $Profession390->save();
        $Profession391= new Profession(); $Profession391->name = 'ZOOTÉCNICO'; $Profession391->description = ''; $Profession391->state = 'ACTIVE'; $Profession391->slug = Str::uuid(); $Profession391->save();

        
    }
}
