<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\Department;
use App\Models\Province;
use App\Models\CantonDistrict;
use App\Models\NeighborhoodCommunity;
use App\Models\Municipality;
use Illuminate\Support\Str;

class SanLorenzoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Distritos

    $CantonDistrict1= new CantonDistrict(); $CantonDistrict1->municipality_id=2; $CantonDistrict1->type='DISTRITO'; $CantonDistrict1->name = 'SAN LORENZO';$CantonDistrict1->description='DISTRITO: 1';$CantonDistrict1->state = 'ACTIVE'; $CantonDistrict1->slug = Str::uuid(); $CantonDistrict1->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict1->save();
    $CantonDistrict2= new CantonDistrict(); $CantonDistrict2->municipality_id=2; $CantonDistrict2->type='DISTRITO'; $CantonDistrict2->name = 'TOMATITAS';$CantonDistrict2->description='DISTRITO: 2';$CantonDistrict2->state = 'ACTIVE'; $CantonDistrict2->slug = Str::uuid(); $CantonDistrict2->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict2->save();
    $CantonDistrict3= new CantonDistrict(); $CantonDistrict3->municipality_id=2; $CantonDistrict3->type='DISTRITO'; $CantonDistrict3->name = 'SANTA BARBARA';$CantonDistrict3->description='DISTRITO: 3';$CantonDistrict3->state = 'ACTIVE'; $CantonDistrict3->slug = Str::uuid(); $CantonDistrict3->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict3->save();
    $CantonDistrict4= new CantonDistrict(); $CantonDistrict4->municipality_id=2; $CantonDistrict4->type='DISTRITO'; $CantonDistrict4->name = 'CHOROMA';$CantonDistrict4->description='DISTRITO: 4';$CantonDistrict4->state = 'ACTIVE'; $CantonDistrict4->slug = Str::uuid(); $CantonDistrict4->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict4->save();
    $CantonDistrict5= new CantonDistrict(); $CantonDistrict5->municipality_id=2; $CantonDistrict5->type='DISTRITO'; $CantonDistrict5->name = 'EUSTAQUIO MENDEZ';$CantonDistrict5->description='DISTRITO: 5';$CantonDistrict5->state = 'ACTIVE'; $CantonDistrict5->slug = Str::uuid(); $CantonDistrict5->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict5->save();
    $CantonDistrict6= new CantonDistrict(); $CantonDistrict6->municipality_id=2; $CantonDistrict6->type='DISTRITO'; $CantonDistrict6->name = 'SELLA MENDEZ';$CantonDistrict6->description='DISTRITO: 6';$CantonDistrict6->state = 'ACTIVE'; $CantonDistrict6->slug = Str::uuid(); $CantonDistrict6->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict6->save();
    $CantonDistrict7= new CantonDistrict(); $CantonDistrict7->municipality_id=2; $CantonDistrict7->type='DISTRITO'; $CantonDistrict7->name = 'EL ROSAL';$CantonDistrict7->description='DISTRITO: 7';$CantonDistrict7->state = 'ACTIVE'; $CantonDistrict7->slug = Str::uuid(); $CantonDistrict7->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict7->save();
    $CantonDistrict8= new CantonDistrict(); $CantonDistrict8->municipality_id=2; $CantonDistrict8->type='DISTRITO'; $CantonDistrict8->name = 'PANTIPAMPA';$CantonDistrict8->description='DISTRITO: 8';$CantonDistrict8->state = 'ACTIVE'; $CantonDistrict8->slug = Str::uuid(); $CantonDistrict8->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict8->save();
    $CantonDistrict9= new CantonDistrict(); $CantonDistrict9->municipality_id=2; $CantonDistrict9->type='DISTRITO'; $CantonDistrict9->name = 'JARCA CANCHA';$CantonDistrict9->description='DISTRITO: 9';$CantonDistrict9->state = 'ACTIVE'; $CantonDistrict9->slug = Str::uuid(); $CantonDistrict9->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict9->save();
    $CantonDistrict10= new CantonDistrict(); $CantonDistrict10->municipality_id=2; $CantonDistrict10->type='DISTRITO'; $CantonDistrict10->name = 'ALTO DE CAJAS';$CantonDistrict10->description='DISTRITO: 10';$CantonDistrict10->state = 'ACTIVE'; $CantonDistrict10->slug = Str::uuid(); $CantonDistrict10->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2'; $CantonDistrict10->save();

    //barrios y comunidades
    $NeighborhoodCommunity1= new NeighborhoodCommunity();$NeighborhoodCommunity1->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity1->type='COMUNIDAD'; $NeighborhoodCommunity1->name = 'VILLA SAN SANTIAGO DE LA BANDA';$NeighborhoodCommunity1->description='COMUNIDAD';$NeighborhoodCommunity1->state = 'ACTIVE'; $NeighborhoodCommunity1->slug = Str::uuid(); $NeighborhoodCommunity1->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity1->save();
    $NeighborhoodCommunity2= new NeighborhoodCommunity();$NeighborhoodCommunity2->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity2->type='COMUNIDAD'; $NeighborhoodCommunity2->name = 'RÍO SECO';$NeighborhoodCommunity2->description='COMUNIDAD';$NeighborhoodCommunity2->state = 'ACTIVE'; $NeighborhoodCommunity2->slug = Str::uuid(); $NeighborhoodCommunity2->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity2->save();
    $NeighborhoodCommunity3= new NeighborhoodCommunity();$NeighborhoodCommunity3->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity3->type='BARRIO'; $NeighborhoodCommunity3->name = 'CENTRAL';$NeighborhoodCommunity3->description='BARRIO';$NeighborhoodCommunity3->state = 'ACTIVE'; $NeighborhoodCommunity3->slug = Str::uuid(); $NeighborhoodCommunity3->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity3->save();
    $NeighborhoodCommunity4= new NeighborhoodCommunity();$NeighborhoodCommunity4->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity4->type='BARRIO'; $NeighborhoodCommunity4->name = 'SAN PEDRO';$NeighborhoodCommunity4->description='BARRIO';$NeighborhoodCommunity4->state = 'ACTIVE'; $NeighborhoodCommunity4->slug = Str::uuid(); $NeighborhoodCommunity4->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity4->save();
    $NeighborhoodCommunity5= new NeighborhoodCommunity();$NeighborhoodCommunity5->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity5->type='BARRIO'; $NeighborhoodCommunity5->name = 'OSCAR ALFARO';$NeighborhoodCommunity5->description='BARRIO';$NeighborhoodCommunity5->state = 'ACTIVE'; $NeighborhoodCommunity5->slug = Str::uuid(); $NeighborhoodCommunity5->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity5->save();
    $NeighborhoodCommunity6= new NeighborhoodCommunity();$NeighborhoodCommunity6->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity6->type='BARRIO'; $NeighborhoodCommunity6->name = 'LA BANDA';$NeighborhoodCommunity6->description='BARRIO';$NeighborhoodCommunity6->state = 'ACTIVE'; $NeighborhoodCommunity6->slug = Str::uuid(); $NeighborhoodCommunity6->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity6->save();
    $NeighborhoodCommunity7= new NeighborhoodCommunity();$NeighborhoodCommunity7->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity7->type='BARRIO'; $NeighborhoodCommunity7->name = 'TARIJA CANCHA SUD';$NeighborhoodCommunity7->description='BARRIO';$NeighborhoodCommunity7->state = 'ACTIVE'; $NeighborhoodCommunity7->slug = Str::uuid(); $NeighborhoodCommunity7->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity7->save();
    $NeighborhoodCommunity8= new NeighborhoodCommunity();$NeighborhoodCommunity8->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity8->type='BARRIO'; $NeighborhoodCommunity8->name = 'TARIJA CANCHA NORTE';$NeighborhoodCommunity8->description='BARRIO';$NeighborhoodCommunity8->state = 'ACTIVE'; $NeighborhoodCommunity8->slug = Str::uuid(); $NeighborhoodCommunity8->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity8->save();
    $NeighborhoodCommunity9= new NeighborhoodCommunity();$NeighborhoodCommunity9->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity9->type='BARRIO'; $NeighborhoodCommunity9->name = 'BORDO EL MOLLAR';$NeighborhoodCommunity9->description='BARRIO';$NeighborhoodCommunity9->state = 'ACTIVE'; $NeighborhoodCommunity9->slug = Str::uuid(); $NeighborhoodCommunity9->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity9->save();
    $NeighborhoodCommunity10= new NeighborhoodCommunity();$NeighborhoodCommunity10->canton_district_id=$CantonDistrict1->id; $NeighborhoodCommunity10->type='BARRIO'; $NeighborhoodCommunity10->name = 'LAJAS';$NeighborhoodCommunity10->description='BARRIO';$NeighborhoodCommunity10->state = 'ACTIVE'; $NeighborhoodCommunity10->slug = Str::uuid(); $NeighborhoodCommunity10->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity10->save();
    $NeighborhoodCommunity11= new NeighborhoodCommunity();$NeighborhoodCommunity11->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity11->type='COMUNIDAD'; $NeighborhoodCommunity11->name = 'TOMATITAS';$NeighborhoodCommunity11->description='COMUNIDAD';$NeighborhoodCommunity11->state = 'ACTIVE'; $NeighborhoodCommunity11->slug = Str::uuid(); $NeighborhoodCommunity11->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity11->save();
    $NeighborhoodCommunity12= new NeighborhoodCommunity();$NeighborhoodCommunity12->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity12->type='COMUNIDAD'; $NeighborhoodCommunity12->name = 'LOMA DE TOMATITAS';$NeighborhoodCommunity12->description='COMUNIDAD';$NeighborhoodCommunity12->state = 'ACTIVE'; $NeighborhoodCommunity12->slug = Str::uuid(); $NeighborhoodCommunity12->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity12->save();
    $NeighborhoodCommunity13= new NeighborhoodCommunity();$NeighborhoodCommunity13->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity13->type='COMUNIDAD'; $NeighborhoodCommunity13->name = 'TOMATITAS NORTE';$NeighborhoodCommunity13->description='COMUNIDAD';$NeighborhoodCommunity13->state = 'ACTIVE'; $NeighborhoodCommunity13->slug = Str::uuid(); $NeighborhoodCommunity13->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity13->save();
    $NeighborhoodCommunity14= new NeighborhoodCommunity();$NeighborhoodCommunity14->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity14->type='COMUNIDAD'; $NeighborhoodCommunity14->name = 'RINCON DE LA VICTORIA';$NeighborhoodCommunity14->description='COMUNIDAD';$NeighborhoodCommunity14->state = 'ACTIVE'; $NeighborhoodCommunity14->slug = Str::uuid(); $NeighborhoodCommunity14->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity14->save();
    $NeighborhoodCommunity15= new NeighborhoodCommunity();$NeighborhoodCommunity15->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity15->type='COMUNIDAD'; $NeighborhoodCommunity15->name = 'LA VICTORIA';$NeighborhoodCommunity15->description='COMUNIDAD';$NeighborhoodCommunity15->state = 'ACTIVE'; $NeighborhoodCommunity15->slug = Str::uuid(); $NeighborhoodCommunity15->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity15->save();
    $NeighborhoodCommunity16= new NeighborhoodCommunity();$NeighborhoodCommunity16->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity16->type='COMUNIDAD'; $NeighborhoodCommunity16->name = 'ERQUIZ SUD';$NeighborhoodCommunity16->description='COMUNIDAD';$NeighborhoodCommunity16->state = 'ACTIVE'; $NeighborhoodCommunity16->slug = Str::uuid(); $NeighborhoodCommunity16->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity16->save();
    $NeighborhoodCommunity17= new NeighborhoodCommunity();$NeighborhoodCommunity17->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity17->type='COMUNIDAD'; $NeighborhoodCommunity17->name = 'ERQUIZ OROPEZA';$NeighborhoodCommunity17->description='COMUNIDAD';$NeighborhoodCommunity17->state = 'ACTIVE'; $NeighborhoodCommunity17->slug = Str::uuid(); $NeighborhoodCommunity17->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity17->save();
    $NeighborhoodCommunity18= new NeighborhoodCommunity();$NeighborhoodCommunity18->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity18->type='COMUNIDAD'; $NeighborhoodCommunity18->name = 'ERQUIZ NORTE';$NeighborhoodCommunity18->description='COMUNIDAD';$NeighborhoodCommunity18->state = 'ACTIVE'; $NeighborhoodCommunity18->slug = Str::uuid(); $NeighborhoodCommunity18->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity18->save();
    $NeighborhoodCommunity19= new NeighborhoodCommunity();$NeighborhoodCommunity19->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity19->type='COMUNIDAD'; $NeighborhoodCommunity19->name = 'ERQUIZ CEIBAL';$NeighborhoodCommunity19->description='COMUNIDAD';$NeighborhoodCommunity19->state = 'ACTIVE'; $NeighborhoodCommunity19->slug = Str::uuid(); $NeighborhoodCommunity19->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity19->save();
    $NeighborhoodCommunity20= new NeighborhoodCommunity();$NeighborhoodCommunity20->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity20->type='COMUNIDAD'; $NeighborhoodCommunity20->name = 'EL CADILLAR';$NeighborhoodCommunity20->description='COMUNIDAD';$NeighborhoodCommunity20->state = 'ACTIVE'; $NeighborhoodCommunity20->slug = Str::uuid(); $NeighborhoodCommunity20->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity20->save();
    $NeighborhoodCommunity21= new NeighborhoodCommunity();$NeighborhoodCommunity21->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity21->type='COMUNIDAD'; $NeighborhoodCommunity21->name = 'COIMATA';$NeighborhoodCommunity21->description='COMUNIDAD';$NeighborhoodCommunity21->state = 'ACTIVE'; $NeighborhoodCommunity21->slug = Str::uuid(); $NeighborhoodCommunity21->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity21->save();
    $NeighborhoodCommunity22= new NeighborhoodCommunity();$NeighborhoodCommunity22->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity22->type='BARRIO'; $NeighborhoodCommunity22->name = 'BARRIO PRIMAVERA-LT';$NeighborhoodCommunity22->description='BARRIO';$NeighborhoodCommunity22->state = 'ACTIVE'; $NeighborhoodCommunity22->slug = Str::uuid(); $NeighborhoodCommunity22->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity22->save();
    $NeighborhoodCommunity23= new NeighborhoodCommunity();$NeighborhoodCommunity23->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity23->type='BARRIO'; $NeighborhoodCommunity23->name = 'MENDEZ FORTALEZA-LT';$NeighborhoodCommunity23->description='BARRIO';$NeighborhoodCommunity23->state = 'ACTIVE'; $NeighborhoodCommunity23->slug = Str::uuid(); $NeighborhoodCommunity23->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity23->save();
    $NeighborhoodCommunity24= new NeighborhoodCommunity();$NeighborhoodCommunity24->canton_district_id=$CantonDistrict2->id; $NeighborhoodCommunity24->type='BARRIO'; $NeighborhoodCommunity24->name = 'ASOCIACION DE VIVIENDAS 10 DE ABRIL-EO';$NeighborhoodCommunity24->description='BARRIO';$NeighborhoodCommunity24->state = 'ACTIVE'; $NeighborhoodCommunity24->slug = Str::uuid(); $NeighborhoodCommunity24->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity24->save();
    $NeighborhoodCommunity25= new NeighborhoodCommunity();$NeighborhoodCommunity25->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity25->type='COMUNIDAD'; $NeighborhoodCommunity25->name = 'SANTA BARBARA CHICA';$NeighborhoodCommunity25->description='COMUNIDAD';$NeighborhoodCommunity25->state = 'ACTIVE'; $NeighborhoodCommunity25->slug = Str::uuid(); $NeighborhoodCommunity25->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity25->save();
    $NeighborhoodCommunity26= new NeighborhoodCommunity();$NeighborhoodCommunity26->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity26->type='COMUNIDAD'; $NeighborhoodCommunity26->name = 'SANTA BARBARA GRANDE';$NeighborhoodCommunity26->description='COMUNIDAD';$NeighborhoodCommunity26->state = 'ACTIVE'; $NeighborhoodCommunity26->slug = Str::uuid(); $NeighborhoodCommunity26->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity26->save();
    $NeighborhoodCommunity27= new NeighborhoodCommunity();$NeighborhoodCommunity27->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity27->type='COMUNIDAD'; $NeighborhoodCommunity27->name = 'RANCHO NORTE';$NeighborhoodCommunity27->description='COMUNIDAD';$NeighborhoodCommunity27->state = 'ACTIVE'; $NeighborhoodCommunity27->slug = Str::uuid(); $NeighborhoodCommunity27->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity27->save();
    $NeighborhoodCommunity28= new NeighborhoodCommunity();$NeighborhoodCommunity28->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity28->type='COMUNIDAD'; $NeighborhoodCommunity28->name = 'RANCHO SUD';$NeighborhoodCommunity28->description='COMUNIDAD';$NeighborhoodCommunity28->state = 'ACTIVE'; $NeighborhoodCommunity28->slug = Str::uuid(); $NeighborhoodCommunity28->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity28->save();
    $NeighborhoodCommunity29= new NeighborhoodCommunity();$NeighborhoodCommunity29->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity29->type='COMUNIDAD'; $NeighborhoodCommunity29->name = 'TUCUMILLA';$NeighborhoodCommunity29->description='COMUNIDAD';$NeighborhoodCommunity29->state = 'ACTIVE'; $NeighborhoodCommunity29->slug = Str::uuid(); $NeighborhoodCommunity29->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity29->save();
    $NeighborhoodCommunity30= new NeighborhoodCommunity();$NeighborhoodCommunity30->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity30->type='BARRIO'; $NeighborhoodCommunity30->name = 'BARRIO LOS PINOS';$NeighborhoodCommunity30->description='BARRIO';$NeighborhoodCommunity30->state = 'ACTIVE'; $NeighborhoodCommunity30->slug = Str::uuid(); $NeighborhoodCommunity30->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity30->save();
    $NeighborhoodCommunity31= new NeighborhoodCommunity();$NeighborhoodCommunity31->canton_district_id=$CantonDistrict3->id; $NeighborhoodCommunity31->type='BARRIO'; $NeighborhoodCommunity31->name = 'ASOCIACION URKUPIÑA';$NeighborhoodCommunity31->description='BARRIO';$NeighborhoodCommunity31->state = 'ACTIVE'; $NeighborhoodCommunity31->slug = Str::uuid(); $NeighborhoodCommunity31->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity31->save();
    $NeighborhoodCommunity32= new NeighborhoodCommunity();$NeighborhoodCommunity32->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity32->type='COMUNIDAD'; $NeighborhoodCommunity32->name = 'COCHAS';$NeighborhoodCommunity32->description='COMUNIDAD';$NeighborhoodCommunity32->state = 'ACTIVE'; $NeighborhoodCommunity32->slug = Str::uuid(); $NeighborhoodCommunity32->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity32->save();
    $NeighborhoodCommunity33= new NeighborhoodCommunity();$NeighborhoodCommunity33->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity33->type='COMUNIDAD'; $NeighborhoodCommunity33->name = 'CHOROMA';$NeighborhoodCommunity33->description='COMUNIDAD';$NeighborhoodCommunity33->state = 'ACTIVE'; $NeighborhoodCommunity33->slug = Str::uuid(); $NeighborhoodCommunity33->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity33->save();
    $NeighborhoodCommunity34= new NeighborhoodCommunity();$NeighborhoodCommunity34->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity34->type='COMUNIDAD'; $NeighborhoodCommunity34->name = 'FALDA LA QUIÑUA';$NeighborhoodCommunity34->description='COMUNIDAD';$NeighborhoodCommunity34->state = 'ACTIVE'; $NeighborhoodCommunity34->slug = Str::uuid(); $NeighborhoodCommunity34->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity34->save();
    $NeighborhoodCommunity35= new NeighborhoodCommunity();$NeighborhoodCommunity35->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity35->type='COMUNIDAD'; $NeighborhoodCommunity35->name = 'LA CALAMA';$NeighborhoodCommunity35->description='COMUNIDAD';$NeighborhoodCommunity35->state = 'ACTIVE'; $NeighborhoodCommunity35->slug = Str::uuid(); $NeighborhoodCommunity35->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity35->save();
    $NeighborhoodCommunity36= new NeighborhoodCommunity();$NeighborhoodCommunity36->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity36->type='COMUNIDAD'; $NeighborhoodCommunity36->name = 'BORDO DE LA CALAMA';$NeighborhoodCommunity36->description='COMUNIDAD';$NeighborhoodCommunity36->state = 'ACTIVE'; $NeighborhoodCommunity36->slug = Str::uuid(); $NeighborhoodCommunity36->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity36->save();
    $NeighborhoodCommunity37= new NeighborhoodCommunity();$NeighborhoodCommunity37->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity37->type='COMUNIDAD'; $NeighborhoodCommunity37->name = 'MARQUIRI';$NeighborhoodCommunity37->description='COMUNIDAD';$NeighborhoodCommunity37->state = 'ACTIVE'; $NeighborhoodCommunity37->slug = Str::uuid(); $NeighborhoodCommunity37->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity37->save();
    $NeighborhoodCommunity38= new NeighborhoodCommunity();$NeighborhoodCommunity38->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity38->type='COMUNIDAD'; $NeighborhoodCommunity38->name = 'PAJCHANI';$NeighborhoodCommunity38->description='COMUNIDAD';$NeighborhoodCommunity38->state = 'ACTIVE'; $NeighborhoodCommunity38->slug = Str::uuid(); $NeighborhoodCommunity38->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity38->save();
    $NeighborhoodCommunity39= new NeighborhoodCommunity();$NeighborhoodCommunity39->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity39->type='COMUNIDAD'; $NeighborhoodCommunity39->name = 'TRES MORROS';$NeighborhoodCommunity39->description='COMUNIDAD';$NeighborhoodCommunity39->state = 'ACTIVE'; $NeighborhoodCommunity39->slug = Str::uuid(); $NeighborhoodCommunity39->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity39->save();
    $NeighborhoodCommunity40= new NeighborhoodCommunity();$NeighborhoodCommunity40->canton_district_id=$CantonDistrict4->id; $NeighborhoodCommunity40->type='COMUNIDAD'; $NeighborhoodCommunity40->name = 'JURINA';$NeighborhoodCommunity40->description='COMUNIDAD';$NeighborhoodCommunity40->state = 'ACTIVE'; $NeighborhoodCommunity40->slug = Str::uuid(); $NeighborhoodCommunity40->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity40->save();
    $NeighborhoodCommunity41= new NeighborhoodCommunity();$NeighborhoodCommunity41->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity41->type='COMUNIDAD'; $NeighborhoodCommunity41->name = 'CARACHIMAYO';$NeighborhoodCommunity41->description='COMUNIDAD';$NeighborhoodCommunity41->state = 'ACTIVE'; $NeighborhoodCommunity41->slug = Str::uuid(); $NeighborhoodCommunity41->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity41->save();
    $NeighborhoodCommunity42= new NeighborhoodCommunity();$NeighborhoodCommunity42->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity42->type='COMUNIDAD'; $NeighborhoodCommunity42->name = 'COLORADOS SUD';$NeighborhoodCommunity42->description='COMUNIDAD';$NeighborhoodCommunity42->state = 'ACTIVE'; $NeighborhoodCommunity42->slug = Str::uuid(); $NeighborhoodCommunity42->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity42->save();
    $NeighborhoodCommunity43= new NeighborhoodCommunity();$NeighborhoodCommunity43->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity43->type='COMUNIDAD'; $NeighborhoodCommunity43->name = 'CANASMORO';$NeighborhoodCommunity43->description='COMUNIDAD';$NeighborhoodCommunity43->state = 'ACTIVE'; $NeighborhoodCommunity43->slug = Str::uuid(); $NeighborhoodCommunity43->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity43->save();
    $NeighborhoodCommunity44= new NeighborhoodCommunity();$NeighborhoodCommunity44->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity44->type='COMUNIDAD'; $NeighborhoodCommunity44->name = 'ALTO DE LAJAS';$NeighborhoodCommunity44->description='COMUNIDAD';$NeighborhoodCommunity44->state = 'ACTIVE'; $NeighborhoodCommunity44->slug = Str::uuid(); $NeighborhoodCommunity44->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity44->save();
    $NeighborhoodCommunity45= new NeighborhoodCommunity();$NeighborhoodCommunity45->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity45->type='COMUNIDAD'; $NeighborhoodCommunity45->name = 'CHAMATA';$NeighborhoodCommunity45->description='COMUNIDAD';$NeighborhoodCommunity45->state = 'ACTIVE'; $NeighborhoodCommunity45->slug = Str::uuid(); $NeighborhoodCommunity45->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity45->save();
    $NeighborhoodCommunity46= new NeighborhoodCommunity();$NeighborhoodCommunity46->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity46->type='COMUNIDAD'; $NeighborhoodCommunity46->name = 'CORANA NORTE';$NeighborhoodCommunity46->description='COMUNIDAD';$NeighborhoodCommunity46->state = 'ACTIVE'; $NeighborhoodCommunity46->slug = Str::uuid(); $NeighborhoodCommunity46->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity46->save();
    $NeighborhoodCommunity47= new NeighborhoodCommunity();$NeighborhoodCommunity47->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity47->type='COMUNIDAD'; $NeighborhoodCommunity47->name = 'CORANA SUD';$NeighborhoodCommunity47->description='COMUNIDAD';$NeighborhoodCommunity47->state = 'ACTIVE'; $NeighborhoodCommunity47->slug = Str::uuid(); $NeighborhoodCommunity47->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity47->save();
    $NeighborhoodCommunity48= new NeighborhoodCommunity();$NeighborhoodCommunity48->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity48->type='COMUNIDAD'; $NeighborhoodCommunity48->name = 'HUACATA';$NeighborhoodCommunity48->description='COMUNIDAD';$NeighborhoodCommunity48->state = 'ACTIVE'; $NeighborhoodCommunity48->slug = Str::uuid(); $NeighborhoodCommunity48->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity48->save();
    $NeighborhoodCommunity49= new NeighborhoodCommunity();$NeighborhoodCommunity49->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity49->type='COMUNIDAD'; $NeighborhoodCommunity49->name = 'LA HONDURA';$NeighborhoodCommunity49->description='COMUNIDAD';$NeighborhoodCommunity49->state = 'ACTIVE'; $NeighborhoodCommunity49->slug = Str::uuid(); $NeighborhoodCommunity49->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity49->save();
    $NeighborhoodCommunity50= new NeighborhoodCommunity();$NeighborhoodCommunity50->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity50->type='COMUNIDAD'; $NeighborhoodCommunity50->name = 'TOMATAS GRANDE';$NeighborhoodCommunity50->description='COMUNIDAD';$NeighborhoodCommunity50->state = 'ACTIVE'; $NeighborhoodCommunity50->slug = Str::uuid(); $NeighborhoodCommunity50->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity50->save();
    $NeighborhoodCommunity51= new NeighborhoodCommunity();$NeighborhoodCommunity51->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity51->type='COMUNIDAD'; $NeighborhoodCommunity51->name = 'TRANCAS';$NeighborhoodCommunity51->description='COMUNIDAD';$NeighborhoodCommunity51->state = 'ACTIVE'; $NeighborhoodCommunity51->slug = Str::uuid(); $NeighborhoodCommunity51->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity51->save();
    $NeighborhoodCommunity52= new NeighborhoodCommunity();$NeighborhoodCommunity52->canton_district_id=$CantonDistrict5->id; $NeighborhoodCommunity52->type='COMUNIDAD'; $NeighborhoodCommunity52->name = 'CARACHIMAYO NORTE';$NeighborhoodCommunity52->description='COMUNIDAD';$NeighborhoodCommunity52->state = 'ACTIVE'; $NeighborhoodCommunity52->slug = Str::uuid(); $NeighborhoodCommunity52->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity52->save();
    $NeighborhoodCommunity53= new NeighborhoodCommunity();$NeighborhoodCommunity53->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity53->type='COMUNIDAD'; $NeighborhoodCommunity53->name = 'SELLA MENDEZ';$NeighborhoodCommunity53->description='COMUNIDAD';$NeighborhoodCommunity53->state = 'ACTIVE'; $NeighborhoodCommunity53->slug = Str::uuid(); $NeighborhoodCommunity53->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity53->save();
    $NeighborhoodCommunity54= new NeighborhoodCommunity();$NeighborhoodCommunity54->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity54->type='COMUNIDAD'; $NeighborhoodCommunity54->name = 'CAÑAHUAYCO';$NeighborhoodCommunity54->description='COMUNIDAD';$NeighborhoodCommunity54->state = 'ACTIVE'; $NeighborhoodCommunity54->slug = Str::uuid(); $NeighborhoodCommunity54->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity54->save();
    $NeighborhoodCommunity55= new NeighborhoodCommunity();$NeighborhoodCommunity55->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity55->type='COMUNIDAD'; $NeighborhoodCommunity55->name = 'CERRO DE PLATA';$NeighborhoodCommunity55->description='COMUNIDAD';$NeighborhoodCommunity55->state = 'ACTIVE'; $NeighborhoodCommunity55->slug = Str::uuid(); $NeighborhoodCommunity55->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity55->save();
    $NeighborhoodCommunity56= new NeighborhoodCommunity();$NeighborhoodCommunity56->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity56->type='COMUNIDAD'; $NeighborhoodCommunity56->name = 'EL BARRANCO';$NeighborhoodCommunity56->description='COMUNIDAD';$NeighborhoodCommunity56->state = 'ACTIVE'; $NeighborhoodCommunity56->slug = Str::uuid(); $NeighborhoodCommunity56->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity56->save();
    $NeighborhoodCommunity57= new NeighborhoodCommunity();$NeighborhoodCommunity57->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity57->type='COMUNIDAD'; $NeighborhoodCommunity57->name = 'MONTE MENDEZ';$NeighborhoodCommunity57->description='COMUNIDAD';$NeighborhoodCommunity57->state = 'ACTIVE'; $NeighborhoodCommunity57->slug = Str::uuid(); $NeighborhoodCommunity57->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity57->save();
    $NeighborhoodCommunity58= new NeighborhoodCommunity();$NeighborhoodCommunity58->canton_district_id=$CantonDistrict6->id; $NeighborhoodCommunity58->type='COMUNIDAD'; $NeighborhoodCommunity58->name = 'ALAYPATA';$NeighborhoodCommunity58->description='COMUNIDAD';$NeighborhoodCommunity58->state = 'ACTIVE'; $NeighborhoodCommunity58->slug = Str::uuid(); $NeighborhoodCommunity58->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity58->save();
    $NeighborhoodCommunity59= new NeighborhoodCommunity();$NeighborhoodCommunity59->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity59->type='COMUNIDAD'; $NeighborhoodCommunity59->name = 'COLORADOS NORTE';$NeighborhoodCommunity59->description='COMUNIDAD';$NeighborhoodCommunity59->state = 'ACTIVE'; $NeighborhoodCommunity59->slug = Str::uuid(); $NeighborhoodCommunity59->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity59->save();
    $NeighborhoodCommunity60= new NeighborhoodCommunity();$NeighborhoodCommunity60->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity60->type='COMUNIDAD'; $NeighborhoodCommunity60->name = 'CRIVA';$NeighborhoodCommunity60->description='COMUNIDAD';$NeighborhoodCommunity60->state = 'ACTIVE'; $NeighborhoodCommunity60->slug = Str::uuid(); $NeighborhoodCommunity60->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity60->save();
    $NeighborhoodCommunity61= new NeighborhoodCommunity();$NeighborhoodCommunity61->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity61->type='COMUNIDAD'; $NeighborhoodCommunity61->name = 'EL ROSAL';$NeighborhoodCommunity61->description='COMUNIDAD';$NeighborhoodCommunity61->state = 'ACTIVE'; $NeighborhoodCommunity61->slug = Str::uuid(); $NeighborhoodCommunity61->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity61->save();
    $NeighborhoodCommunity62= new NeighborhoodCommunity();$NeighborhoodCommunity62->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity62->type='COMUNIDAD'; $NeighborhoodCommunity62->name = 'HUANCOIRO';$NeighborhoodCommunity62->description='COMUNIDAD';$NeighborhoodCommunity62->state = 'ACTIVE'; $NeighborhoodCommunity62->slug = Str::uuid(); $NeighborhoodCommunity62->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity62->save();
    $NeighborhoodCommunity63= new NeighborhoodCommunity();$NeighborhoodCommunity63->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity63->type='COMUNIDAD'; $NeighborhoodCommunity63->name = 'LEON CANCHA';$NeighborhoodCommunity63->description='COMUNIDAD';$NeighborhoodCommunity63->state = 'ACTIVE'; $NeighborhoodCommunity63->slug = Str::uuid(); $NeighborhoodCommunity63->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity63->save();
    $NeighborhoodCommunity64= new NeighborhoodCommunity();$NeighborhoodCommunity64->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity64->type='COMUNIDAD'; $NeighborhoodCommunity64->name = 'NOGALITOS';$NeighborhoodCommunity64->description='COMUNIDAD';$NeighborhoodCommunity64->state = 'ACTIVE'; $NeighborhoodCommunity64->slug = Str::uuid(); $NeighborhoodCommunity64->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity64->save();
    $NeighborhoodCommunity65= new NeighborhoodCommunity();$NeighborhoodCommunity65->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity65->type='COMUNIDAD'; $NeighborhoodCommunity65->name = 'NOQUES';$NeighborhoodCommunity65->description='COMUNIDAD';$NeighborhoodCommunity65->state = 'ACTIVE'; $NeighborhoodCommunity65->slug = Str::uuid(); $NeighborhoodCommunity65->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity65->save();
    $NeighborhoodCommunity66= new NeighborhoodCommunity();$NeighborhoodCommunity66->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity66->type='COMUNIDAD'; $NeighborhoodCommunity66->name = 'PALACIOS';$NeighborhoodCommunity66->description='COMUNIDAD';$NeighborhoodCommunity66->state = 'ACTIVE'; $NeighborhoodCommunity66->slug = Str::uuid(); $NeighborhoodCommunity66->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity66->save();
    $NeighborhoodCommunity67= new NeighborhoodCommunity();$NeighborhoodCommunity67->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity67->type='COMUNIDAD'; $NeighborhoodCommunity67->name = 'SAN ISIDRO';$NeighborhoodCommunity67->description='COMUNIDAD';$NeighborhoodCommunity67->state = 'ACTIVE'; $NeighborhoodCommunity67->slug = Str::uuid(); $NeighborhoodCommunity67->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity67->save();
    $NeighborhoodCommunity68= new NeighborhoodCommunity();$NeighborhoodCommunity68->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity68->type='COMUNIDAD'; $NeighborhoodCommunity68->name = 'YUMASA';$NeighborhoodCommunity68->description='COMUNIDAD';$NeighborhoodCommunity68->state = 'ACTIVE'; $NeighborhoodCommunity68->slug = Str::uuid(); $NeighborhoodCommunity68->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity68->save();
    $NeighborhoodCommunity69= new NeighborhoodCommunity();$NeighborhoodCommunity69->canton_district_id=$CantonDistrict7->id; $NeighborhoodCommunity69->type='COMUNIDAD'; $NeighborhoodCommunity69->name = 'ZAPATERA';$NeighborhoodCommunity69->description='COMUNIDAD';$NeighborhoodCommunity69->state = 'ACTIVE'; $NeighborhoodCommunity69->slug = Str::uuid(); $NeighborhoodCommunity69->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity69->save();
    $NeighborhoodCommunity70= new NeighborhoodCommunity();$NeighborhoodCommunity70->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity70->type='COMUNIDAD'; $NeighborhoodCommunity70->name = 'ACHERAL';$NeighborhoodCommunity70->description='COMUNIDAD';$NeighborhoodCommunity70->state = 'ACTIVE'; $NeighborhoodCommunity70->slug = Str::uuid(); $NeighborhoodCommunity70->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity70->save();
    $NeighborhoodCommunity71= new NeighborhoodCommunity();$NeighborhoodCommunity71->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity71->type='COMUNIDAD'; $NeighborhoodCommunity71->name = 'ALPAHUASI';$NeighborhoodCommunity71->description='COMUNIDAD';$NeighborhoodCommunity71->state = 'ACTIVE'; $NeighborhoodCommunity71->slug = Str::uuid(); $NeighborhoodCommunity71->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity71->save();
    $NeighborhoodCommunity72= new NeighborhoodCommunity();$NeighborhoodCommunity72->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity72->type='COMUNIDAD'; $NeighborhoodCommunity72->name = 'HOYADAS';$NeighborhoodCommunity72->description='COMUNIDAD';$NeighborhoodCommunity72->state = 'ACTIVE'; $NeighborhoodCommunity72->slug = Str::uuid(); $NeighborhoodCommunity72->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity72->save();
    $NeighborhoodCommunity73= new NeighborhoodCommunity();$NeighborhoodCommunity73->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity73->type='COMUNIDAD'; $NeighborhoodCommunity73->name = 'MANDOR CHICO';$NeighborhoodCommunity73->description='COMUNIDAD';$NeighborhoodCommunity73->state = 'ACTIVE'; $NeighborhoodCommunity73->slug = Str::uuid(); $NeighborhoodCommunity73->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity73->save();
    $NeighborhoodCommunity74= new NeighborhoodCommunity();$NeighborhoodCommunity74->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity74->type='COMUNIDAD'; $NeighborhoodCommunity74->name = 'MANDOR GRANDE';$NeighborhoodCommunity74->description='COMUNIDAD';$NeighborhoodCommunity74->state = 'ACTIVE'; $NeighborhoodCommunity74->slug = Str::uuid(); $NeighborhoodCommunity74->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity74->save();
    $NeighborhoodCommunity75= new NeighborhoodCommunity();$NeighborhoodCommunity75->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity75->type='COMUNIDAD'; $NeighborhoodCommunity75->name = 'PANTIPAMPA';$NeighborhoodCommunity75->description='COMUNIDAD';$NeighborhoodCommunity75->state = 'ACTIVE'; $NeighborhoodCommunity75->slug = Str::uuid(); $NeighborhoodCommunity75->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity75->save();
    $NeighborhoodCommunity76= new NeighborhoodCommunity();$NeighborhoodCommunity76->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity76->type='COMUNIDAD'; $NeighborhoodCommunity76->name = 'QUIRUSILLAS';$NeighborhoodCommunity76->description='COMUNIDAD';$NeighborhoodCommunity76->state = 'ACTIVE'; $NeighborhoodCommunity76->slug = Str::uuid(); $NeighborhoodCommunity76->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity76->save();
    $NeighborhoodCommunity77= new NeighborhoodCommunity();$NeighborhoodCommunity77->canton_district_id=$CantonDistrict8->id; $NeighborhoodCommunity77->type='COMUNIDAD'; $NeighborhoodCommunity77->name = 'SAN PEDRO DE LAS PEÑAS';$NeighborhoodCommunity77->description='COMUNIDAD';$NeighborhoodCommunity77->state = 'ACTIVE'; $NeighborhoodCommunity77->slug = Str::uuid(); $NeighborhoodCommunity77->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity77->save();
    $NeighborhoodCommunity78= new NeighborhoodCommunity();$NeighborhoodCommunity78->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity78->type='COMUNIDAD'; $NeighborhoodCommunity78->name = 'JARCA CANCHA';$NeighborhoodCommunity78->description='COMUNIDAD';$NeighborhoodCommunity78->state = 'ACTIVE'; $NeighborhoodCommunity78->slug = Str::uuid(); $NeighborhoodCommunity78->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity78->save();
    $NeighborhoodCommunity79= new NeighborhoodCommunity();$NeighborhoodCommunity79->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity79->type='COMUNIDAD'; $NeighborhoodCommunity79->name = 'CAMARON';$NeighborhoodCommunity79->description='COMUNIDAD';$NeighborhoodCommunity79->state = 'ACTIVE'; $NeighborhoodCommunity79->slug = Str::uuid(); $NeighborhoodCommunity79->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity79->save();
    $NeighborhoodCommunity80= new NeighborhoodCommunity();$NeighborhoodCommunity80->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity80->type='COMUNIDAD'; $NeighborhoodCommunity80->name = 'CAMPANARIO';$NeighborhoodCommunity80->description='COMUNIDAD';$NeighborhoodCommunity80->state = 'ACTIVE'; $NeighborhoodCommunity80->slug = Str::uuid(); $NeighborhoodCommunity80->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity80->save();
    $NeighborhoodCommunity81= new NeighborhoodCommunity();$NeighborhoodCommunity81->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity81->type='COMUNIDAD'; $NeighborhoodCommunity81->name = 'CERRO REDONDO';$NeighborhoodCommunity81->description='COMUNIDAD';$NeighborhoodCommunity81->state = 'ACTIVE'; $NeighborhoodCommunity81->slug = Str::uuid(); $NeighborhoodCommunity81->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity81->save();
    $NeighborhoodCommunity82= new NeighborhoodCommunity();$NeighborhoodCommunity82->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity82->type='COMUNIDAD'; $NeighborhoodCommunity82->name = 'LLUSCANI';$NeighborhoodCommunity82->description='COMUNIDAD';$NeighborhoodCommunity82->state = 'ACTIVE'; $NeighborhoodCommunity82->slug = Str::uuid(); $NeighborhoodCommunity82->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity82->save();
    $NeighborhoodCommunity83= new NeighborhoodCommunity();$NeighborhoodCommunity83->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity83->type='COMUNIDAD'; $NeighborhoodCommunity83->name = 'MELON PUJIO';$NeighborhoodCommunity83->description='COMUNIDAD';$NeighborhoodCommunity83->state = 'ACTIVE'; $NeighborhoodCommunity83->slug = Str::uuid(); $NeighborhoodCommunity83->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity83->save();
    $NeighborhoodCommunity84= new NeighborhoodCommunity();$NeighborhoodCommunity84->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity84->type='COMUNIDAD'; $NeighborhoodCommunity84->name = 'MOLLE HUAYCO';$NeighborhoodCommunity84->description='COMUNIDAD';$NeighborhoodCommunity84->state = 'ACTIVE'; $NeighborhoodCommunity84->slug = Str::uuid(); $NeighborhoodCommunity84->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity84->save();
    $NeighborhoodCommunity85= new NeighborhoodCommunity();$NeighborhoodCommunity85->canton_district_id=$CantonDistrict9->id; $NeighborhoodCommunity85->type='COMUNIDAD'; $NeighborhoodCommunity85->name = 'PAMPA GRANDE';$NeighborhoodCommunity85->description='COMUNIDAD';$NeighborhoodCommunity85->state = 'ACTIVE'; $NeighborhoodCommunity85->slug = Str::uuid(); $NeighborhoodCommunity85->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity85->save();
    $NeighborhoodCommunity86= new NeighborhoodCommunity();$NeighborhoodCommunity86->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity86->type='COMUNIDAD'; $NeighborhoodCommunity86->name = 'ALISAR LA TORRE';$NeighborhoodCommunity86->description='COMUNIDAD';$NeighborhoodCommunity86->state = 'ACTIVE'; $NeighborhoodCommunity86->slug = Str::uuid(); $NeighborhoodCommunity86->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity86->save();
    $NeighborhoodCommunity87= new NeighborhoodCommunity();$NeighborhoodCommunity87->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity87->type='COMUNIDAD'; $NeighborhoodCommunity87->name = 'ALTO DE CAJAS';$NeighborhoodCommunity87->description='COMUNIDAD';$NeighborhoodCommunity87->state = 'ACTIVE'; $NeighborhoodCommunity87->slug = Str::uuid(); $NeighborhoodCommunity87->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity87->save();
    $NeighborhoodCommunity88= new NeighborhoodCommunity();$NeighborhoodCommunity88->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity88->type='COMUNIDAD'; $NeighborhoodCommunity88->name = 'EL NOGAL';$NeighborhoodCommunity88->description='COMUNIDAD';$NeighborhoodCommunity88->state = 'ACTIVE'; $NeighborhoodCommunity88->slug = Str::uuid(); $NeighborhoodCommunity88->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity88->save();
    $NeighborhoodCommunity89= new NeighborhoodCommunity();$NeighborhoodCommunity89->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity89->type='COMUNIDAD'; $NeighborhoodCommunity89->name = 'EL PUESTO';$NeighborhoodCommunity89->description='COMUNIDAD';$NeighborhoodCommunity89->state = 'ACTIVE'; $NeighborhoodCommunity89->slug = Str::uuid(); $NeighborhoodCommunity89->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity89->save();
    $NeighborhoodCommunity90= new NeighborhoodCommunity();$NeighborhoodCommunity90->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity90->type='COMUNIDAD'; $NeighborhoodCommunity90->name = 'JARCAS';$NeighborhoodCommunity90->description='COMUNIDAD';$NeighborhoodCommunity90->state = 'ACTIVE'; $NeighborhoodCommunity90->slug = Str::uuid(); $NeighborhoodCommunity90->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity90->save();
    $NeighborhoodCommunity91= new NeighborhoodCommunity();$NeighborhoodCommunity91->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity91->type='COMUNIDAD'; $NeighborhoodCommunity91->name = 'PAJONALCITO';$NeighborhoodCommunity91->description='COMUNIDAD';$NeighborhoodCommunity91->state = 'ACTIVE'; $NeighborhoodCommunity91->slug = Str::uuid(); $NeighborhoodCommunity91->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity91->save();
    $NeighborhoodCommunity92= new NeighborhoodCommunity();$NeighborhoodCommunity92->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity92->type='COMUNIDAD'; $NeighborhoodCommunity92->name = 'PEÑADERIA';$NeighborhoodCommunity92->description='COMUNIDAD';$NeighborhoodCommunity92->state = 'ACTIVE'; $NeighborhoodCommunity92->slug = Str::uuid(); $NeighborhoodCommunity92->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity92->save();
    $NeighborhoodCommunity93= new NeighborhoodCommunity();$NeighborhoodCommunity93->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity93->type='COMUNIDAD'; $NeighborhoodCommunity93->name = 'QUEBRADA DE CAJAS';$NeighborhoodCommunity93->description='COMUNIDAD';$NeighborhoodCommunity93->state = 'ACTIVE'; $NeighborhoodCommunity93->slug = Str::uuid(); $NeighborhoodCommunity93->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity93->save();
    $NeighborhoodCommunity94= new NeighborhoodCommunity();$NeighborhoodCommunity94->canton_district_id=$CantonDistrict10->id; $NeighborhoodCommunity94->type='COMUNIDAD'; $NeighborhoodCommunity94->name = 'SAN LORENCITO';$NeighborhoodCommunity94->description='COMUNIDAD';$NeighborhoodCommunity94->state = 'ACTIVE'; $NeighborhoodCommunity94->slug = Str::uuid(); $NeighborhoodCommunity94->subgovernment_code = '96b0e2aa-199b-4036-8524-0090316068d2';  $NeighborhoodCommunity94->save();



    }
}
