<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Unit;
use Illuminate\Support\Str;

class UnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Unidad_Medida1= new Unit();$Unidad_Medida1->name='1/2 LITROS';$Unidad_Medida1->state = 'ACTIVO';$Unidad_Medida1->slug = Str::uuid();$Unidad_Medida1->save();
        $Unidad_Medida2= new Unit();$Unidad_Medida2->name='1/4 LITROS ';$Unidad_Medida2->state = 'ACTIVO';$Unidad_Medida2->slug = Str::uuid();$Unidad_Medida2->save();
        $Unidad_Medida3= new Unit();$Unidad_Medida3->name='ADHESIVO';$Unidad_Medida3->state = 'ACTIVO';$Unidad_Medida3->slug = Str::uuid();$Unidad_Medida3->save();
        $Unidad_Medida4= new Unit();$Unidad_Medida4->name='AFICHES';$Unidad_Medida4->state = 'ACTIVO';$Unidad_Medida4->slug = Str::uuid();$Unidad_Medida4->save();
        $Unidad_Medida5= new Unit();$Unidad_Medida5->name='ALOJAMIENTO';$Unidad_Medida5->state = 'ACTIVO';$Unidad_Medida5->slug = Str::uuid();$Unidad_Medida5->save();
        $Unidad_Medida6= new Unit();$Unidad_Medida6->name='AMBIENTE';$Unidad_Medida6->state = 'ACTIVO';$Unidad_Medida6->slug = Str::uuid();$Unidad_Medida6->save();
        $Unidad_Medida7= new Unit();$Unidad_Medida7->name='ANALISIS';$Unidad_Medida7->state = 'ACTIVO';$Unidad_Medida7->slug = Str::uuid();$Unidad_Medida7->save();
        $Unidad_Medida8= new Unit();$Unidad_Medida8->name='ANILLADO';$Unidad_Medida8->state = 'ACTIVO';$Unidad_Medida8->slug = Str::uuid();$Unidad_Medida8->save();
        $Unidad_Medida9= new Unit();$Unidad_Medida9->name='ANIMALES';$Unidad_Medida9->state = 'ACTIVO';$Unidad_Medida9->slug = Str::uuid();$Unidad_Medida9->save();
        $Unidad_Medida10= new Unit();$Unidad_Medida10->name='ARROBA';$Unidad_Medida10->state = 'ACTIVO';$Unidad_Medida10->slug = Str::uuid();$Unidad_Medida10->save();
        $Unidad_Medida11= new Unit();$Unidad_Medida11->name='ATENCION';$Unidad_Medida11->state = 'ACTIVO';$Unidad_Medida11->slug = Str::uuid();$Unidad_Medida11->save();
        $Unidad_Medida12= new Unit();$Unidad_Medida12->name='AVES';$Unidad_Medida12->state = 'ACTIVO';$Unidad_Medida12->slug = Str::uuid();$Unidad_Medida12->save();
        $Unidad_Medida13= new Unit();$Unidad_Medida13->name='BALDE';$Unidad_Medida13->state = 'ACTIVO';$Unidad_Medida13->slug = Str::uuid();$Unidad_Medida13->save();
        $Unidad_Medida14= new Unit();$Unidad_Medida14->name='BALON';$Unidad_Medida14->state = 'ACTIVO';$Unidad_Medida14->slug = Str::uuid();$Unidad_Medida14->save();
        $Unidad_Medida15= new Unit();$Unidad_Medida15->name='BARRA';$Unidad_Medida15->state = 'ACTIVO';$Unidad_Medida15->slug = Str::uuid();$Unidad_Medida15->save();
        $Unidad_Medida16= new Unit();$Unidad_Medida16->name='BASTIDOR';$Unidad_Medida16->state = 'ACTIVO';$Unidad_Medida16->slug = Str::uuid();$Unidad_Medida16->save();
        $Unidad_Medida17= new Unit();$Unidad_Medida17->name='BIDON ';$Unidad_Medida17->state = 'ACTIVO';$Unidad_Medida17->slug = Str::uuid();$Unidad_Medida17->save();
        $Unidad_Medida18= new Unit();$Unidad_Medida18->name='BIPTICOS';$Unidad_Medida18->state = 'ACTIVO';$Unidad_Medida18->slug = Str::uuid();$Unidad_Medida18->save();
        $Unidad_Medida19= new Unit();$Unidad_Medida19->name='BLISTER';$Unidad_Medida19->state = 'ACTIVO';$Unidad_Medida19->slug = Str::uuid();$Unidad_Medida19->save();
        $Unidad_Medida20= new Unit();$Unidad_Medida20->name='BLOCK';$Unidad_Medida20->state = 'ACTIVO';$Unidad_Medida20->slug = Str::uuid();$Unidad_Medida20->save();
        $Unidad_Medida21= new Unit();$Unidad_Medida21->name='BOLSA';$Unidad_Medida21->state = 'ACTIVO';$Unidad_Medida21->slug = Str::uuid();$Unidad_Medida21->save();
        $Unidad_Medida22= new Unit();$Unidad_Medida22->name='BOLSA DE 20 KG.';$Unidad_Medida22->state = 'ACTIVO';$Unidad_Medida22->slug = Str::uuid();$Unidad_Medida22->save();
        $Unidad_Medida23= new Unit();$Unidad_Medida23->name='BOLSA QUINTALERA';$Unidad_Medida23->state = 'ACTIVO';$Unidad_Medida23->slug = Str::uuid();$Unidad_Medida23->save();
        $Unidad_Medida24= new Unit();$Unidad_Medida24->name='BOLSAS DE 50 KG';$Unidad_Medida24->state = 'ACTIVO';$Unidad_Medida24->slug = Str::uuid();$Unidad_Medida24->save();
        $Unidad_Medida25= new Unit();$Unidad_Medida25->name='BOTE';$Unidad_Medida25->state = 'ACTIVO';$Unidad_Medida25->slug = Str::uuid();$Unidad_Medida25->save();
        $Unidad_Medida26= new Unit();$Unidad_Medida26->name='BOTELLA ';$Unidad_Medida26->state = 'ACTIVO';$Unidad_Medida26->slug = Str::uuid();$Unidad_Medida26->save();
        $Unidad_Medida27= new Unit();$Unidad_Medida27->name='BOTELLON';$Unidad_Medida27->state = 'ACTIVO';$Unidad_Medida27->slug = Str::uuid();$Unidad_Medida27->save();
        $Unidad_Medida28= new Unit();$Unidad_Medida28->name='BOWLS';$Unidad_Medida28->state = 'ACTIVO';$Unidad_Medida28->slug = Str::uuid();$Unidad_Medida28->save();
        $Unidad_Medida29= new Unit();$Unidad_Medida29->name='C/U';$Unidad_Medida29->state = 'ACTIVO';$Unidad_Medida29->slug = Str::uuid();$Unidad_Medida29->save();
        $Unidad_Medida30= new Unit();$Unidad_Medida30->name='Cabeza';$Unidad_Medida30->state = 'ACTIVO';$Unidad_Medida30->slug = Str::uuid();$Unidad_Medida30->save();
        $Unidad_Medida31= new Unit();$Unidad_Medida31->name='CAJA';$Unidad_Medida31->state = 'ACTIVO';$Unidad_Medida31->slug = Str::uuid();$Unidad_Medida31->save();
        $Unidad_Medida32= new Unit();$Unidad_Medida32->name='CAJA (100 UNID.)';$Unidad_Medida32->state = 'ACTIVO';$Unidad_Medida32->slug = Str::uuid();$Unidad_Medida32->save();
        $Unidad_Medida33= new Unit();$Unidad_Medida33->name='CAMION';$Unidad_Medida33->state = 'ACTIVO';$Unidad_Medida33->slug = Str::uuid();$Unidad_Medida33->save();
        $Unidad_Medida34= new Unit();$Unidad_Medida34->name='CARGADO';$Unidad_Medida34->state = 'ACTIVO';$Unidad_Medida34->slug = Str::uuid();$Unidad_Medida34->save();
        $Unidad_Medida35= new Unit();$Unidad_Medida35->name='CARGAS';$Unidad_Medida35->state = 'ACTIVO';$Unidad_Medida35->slug = Str::uuid();$Unidad_Medida35->save();
        $Unidad_Medida36= new Unit();$Unidad_Medida36->name='CARPA';$Unidad_Medida36->state = 'ACTIVO';$Unidad_Medida36->slug = Str::uuid();$Unidad_Medida36->save();
        $Unidad_Medida37= new Unit();$Unidad_Medida37->name='CARRETE';$Unidad_Medida37->state = 'ACTIVO';$Unidad_Medida37->slug = Str::uuid();$Unidad_Medida37->save();
        $Unidad_Medida38= new Unit();$Unidad_Medida38->name='CARTILLA';$Unidad_Medida38->state = 'ACTIVO';$Unidad_Medida38->slug = Str::uuid();$Unidad_Medida38->save();
        $Unidad_Medida39= new Unit();$Unidad_Medida39->name='CARTUCHO';$Unidad_Medida39->state = 'ACTIVO';$Unidad_Medida39->slug = Str::uuid();$Unidad_Medida39->save();
        $Unidad_Medida40= new Unit();$Unidad_Medida40->name='COMPRIMIDO';$Unidad_Medida40->state = 'ACTIVO';$Unidad_Medida40->slug = Str::uuid();$Unidad_Medida40->save();
        $Unidad_Medida41= new Unit();$Unidad_Medida41->name='CONJUNTO';$Unidad_Medida41->state = 'ACTIVO';$Unidad_Medida41->slug = Str::uuid();$Unidad_Medida41->save();
        $Unidad_Medida42= new Unit();$Unidad_Medida42->name='CONO';$Unidad_Medida42->state = 'ACTIVO';$Unidad_Medida42->slug = Str::uuid();$Unidad_Medida42->save();
        $Unidad_Medida43= new Unit();$Unidad_Medida43->name='COPIA';$Unidad_Medida43->state = 'ACTIVO';$Unidad_Medida43->slug = Str::uuid();$Unidad_Medida43->save();
        $Unidad_Medida44= new Unit();$Unidad_Medida44->name='CUARTILLA ';$Unidad_Medida44->state = 'ACTIVO';$Unidad_Medida44->slug = Str::uuid();$Unidad_Medida44->save();
        $Unidad_Medida45= new Unit();$Unidad_Medida45->name='CUBOS ';$Unidad_Medida45->state = 'ACTIVO';$Unidad_Medida45->slug = Str::uuid();$Unidad_Medida45->save();
        $Unidad_Medida46= new Unit();$Unidad_Medida46->name='DIA';$Unidad_Medida46->state = 'ACTIVO';$Unidad_Medida46->slug = Str::uuid();$Unidad_Medida46->save();
        $Unidad_Medida47= new Unit();$Unidad_Medida47->name='DIESEL';$Unidad_Medida47->state = 'ACTIVO';$Unidad_Medida47->slug = Str::uuid();$Unidad_Medida47->save();
        $Unidad_Medida48= new Unit();$Unidad_Medida48->name='DISE&Ntilde;O';$Unidad_Medida48->state = 'ACTIVO';$Unidad_Medida48->slug = Str::uuid();$Unidad_Medida48->save();
        $Unidad_Medida49= new Unit();$Unidad_Medida49->name='DOCENA';$Unidad_Medida49->state = 'ACTIVO';$Unidad_Medida49->slug = Str::uuid();$Unidad_Medida49->save();
        $Unidad_Medida50= new Unit();$Unidad_Medida50->name='DOCUMENTO';$Unidad_Medida50->state = 'ACTIVO';$Unidad_Medida50->slug = Str::uuid();$Unidad_Medida50->save();
        $Unidad_Medida51= new Unit();$Unidad_Medida51->name='DOMINIO';$Unidad_Medida51->state = 'ACTIVO';$Unidad_Medida51->slug = Str::uuid();$Unidad_Medida51->save();
        $Unidad_Medida52= new Unit();$Unidad_Medida52->name='EJEMPLAR';$Unidad_Medida52->state = 'ACTIVO';$Unidad_Medida52->slug = Str::uuid();$Unidad_Medida52->save();
        $Unidad_Medida53= new Unit();$Unidad_Medida53->name='EJEMPLARES -CD S ';$Unidad_Medida53->state = 'ACTIVO';$Unidad_Medida53->slug = Str::uuid();$Unidad_Medida53->save();
        $Unidad_Medida54= new Unit();$Unidad_Medida54->name='EMPANADAS';$Unidad_Medida54->state = 'ACTIVO';$Unidad_Medida54->slug = Str::uuid();$Unidad_Medida54->save();
        $Unidad_Medida55= new Unit();$Unidad_Medida55->name='EMPASTADOS';$Unidad_Medida55->state = 'ACTIVO';$Unidad_Medida55->slug = Str::uuid();$Unidad_Medida55->save();
        $Unidad_Medida56= new Unit();$Unidad_Medida56->name='ENVASE';$Unidad_Medida56->state = 'ACTIVO';$Unidad_Medida56->slug = Str::uuid();$Unidad_Medida56->save();
        $Unidad_Medida57= new Unit();$Unidad_Medida57->name='EQUIPO';$Unidad_Medida57->state = 'ACTIVO';$Unidad_Medida57->slug = Str::uuid();$Unidad_Medida57->save();
        $Unidad_Medida58= new Unit();$Unidad_Medida58->name='ESTUCHE';$Unidad_Medida58->state = 'ACTIVO';$Unidad_Medida58->slug = Str::uuid();$Unidad_Medida58->save();
        $Unidad_Medida59= new Unit();$Unidad_Medida59->name='FACILITADOR ';$Unidad_Medida59->state = 'ACTIVO';$Unidad_Medida59->slug = Str::uuid();$Unidad_Medida59->save();
        $Unidad_Medida60= new Unit();$Unidad_Medida60->name='FOLDER';$Unidad_Medida60->state = 'ACTIVO';$Unidad_Medida60->slug = Str::uuid();$Unidad_Medida60->save();
        $Unidad_Medida61= new Unit();$Unidad_Medida61->name='FOTOCOPIAS';$Unidad_Medida61->state = 'ACTIVO';$Unidad_Medida61->slug = Str::uuid();$Unidad_Medida61->save();
        $Unidad_Medida62= new Unit();$Unidad_Medida62->name='FRASCO  ';$Unidad_Medida62->state = 'ACTIVO';$Unidad_Medida62->slug = Str::uuid();$Unidad_Medida62->save();
        $Unidad_Medida63= new Unit();$Unidad_Medida63->name='FRASCO 100 ml';$Unidad_Medida63->state = 'ACTIVO';$Unidad_Medida63->slug = Str::uuid();$Unidad_Medida63->save();
        $Unidad_Medida64= new Unit();$Unidad_Medida64->name='FRASCO 250 ml ';$Unidad_Medida64->state = 'ACTIVO';$Unidad_Medida64->slug = Str::uuid();$Unidad_Medida64->save();
        $Unidad_Medida65= new Unit();$Unidad_Medida65->name='FRASCO 50 ml';$Unidad_Medida65->state = 'ACTIVO';$Unidad_Medida65->slug = Str::uuid();$Unidad_Medida65->save();
        $Unidad_Medida66= new Unit();$Unidad_Medida66->name='FRASCO 500 ml';$Unidad_Medida66->state = 'ACTIVO';$Unidad_Medida66->slug = Str::uuid();$Unidad_Medida66->save();
        $Unidad_Medida67= new Unit();$Unidad_Medida67->name='FRASCO 500ml';$Unidad_Medida67->state = 'ACTIVO';$Unidad_Medida67->slug = Str::uuid();$Unidad_Medida67->save();
        $Unidad_Medida68= new Unit();$Unidad_Medida68->name='Frasco de Litro';$Unidad_Medida68->state = 'ACTIVO';$Unidad_Medida68->slug = Str::uuid();$Unidad_Medida68->save();
        $Unidad_Medida69= new Unit();$Unidad_Medida69->name='Frascos de Kg';$Unidad_Medida69->state = 'ACTIVO';$Unidad_Medida69->slug = Str::uuid();$Unidad_Medida69->save();
        $Unidad_Medida70= new Unit();$Unidad_Medida70->name='GALON';$Unidad_Medida70->state = 'ACTIVO';$Unidad_Medida70->slug = Str::uuid();$Unidad_Medida70->save();
        $Unidad_Medida71= new Unit();$Unidad_Medida71->name='GARRAFA';$Unidad_Medida71->state = 'ACTIVO';$Unidad_Medida71->slug = Str::uuid();$Unidad_Medida71->save();
        $Unidad_Medida72= new Unit();$Unidad_Medida72->name='GIGANTOGRAFIAS';$Unidad_Medida72->state = 'ACTIVO';$Unidad_Medida72->slug = Str::uuid();$Unidad_Medida72->save();
        $Unidad_Medida73= new Unit();$Unidad_Medida73->name='GLOBAL (Servicio)';$Unidad_Medida73->state = 'ACTIVO';$Unidad_Medida73->slug = Str::uuid();$Unidad_Medida73->save();
        $Unidad_Medida74= new Unit();$Unidad_Medida74->name='GOTERO';$Unidad_Medida74->state = 'ACTIVO';$Unidad_Medida74->slug = Str::uuid();$Unidad_Medida74->save();
        $Unidad_Medida75= new Unit();$Unidad_Medida75->name='GRAMOS';$Unidad_Medida75->state = 'ACTIVO';$Unidad_Medida75->slug = Str::uuid();$Unidad_Medida75->save();
        $Unidad_Medida76= new Unit();$Unidad_Medida76->name='HOJA';$Unidad_Medida76->state = 'ACTIVO';$Unidad_Medida76->slug = Str::uuid();$Unidad_Medida76->save();
        $Unidad_Medida77= new Unit();$Unidad_Medida77->name='HORAS';$Unidad_Medida77->state = 'ACTIVO';$Unidad_Medida77->slug = Str::uuid();$Unidad_Medida77->save();
        $Unidad_Medida78= new Unit();$Unidad_Medida78->name='HOSPEDAJE';$Unidad_Medida78->state = 'ACTIVO';$Unidad_Medida78->slug = Str::uuid();$Unidad_Medida78->save();
        $Unidad_Medida79= new Unit();$Unidad_Medida79->name='IMPRENTA GLOBAL ';$Unidad_Medida79->state = 'ACTIVO';$Unidad_Medida79->slug = Str::uuid();$Unidad_Medida79->save();
        $Unidad_Medida80= new Unit();$Unidad_Medida80->name='IMPRESION';$Unidad_Medida80->state = 'ACTIVO';$Unidad_Medida80->slug = Str::uuid();$Unidad_Medida80->save();
        $Unidad_Medida81= new Unit();$Unidad_Medida81->name='JUEGO';$Unidad_Medida81->state = 'ACTIVO';$Unidad_Medida81->slug = Str::uuid();$Unidad_Medida81->save();
        $Unidad_Medida82= new Unit();$Unidad_Medida82->name='KG';$Unidad_Medida82->state = 'ACTIVO';$Unidad_Medida82->slug = Str::uuid();$Unidad_Medida82->save();
        $Unidad_Medida83= new Unit();$Unidad_Medida83->name='KILOGRAMO';$Unidad_Medida83->state = 'ACTIVO';$Unidad_Medida83->slug = Str::uuid();$Unidad_Medida83->save();
        $Unidad_Medida84= new Unit();$Unidad_Medida84->name='KIT';$Unidad_Medida84->state = 'ACTIVO';$Unidad_Medida84->slug = Str::uuid();$Unidad_Medida84->save();
        $Unidad_Medida85= new Unit();$Unidad_Medida85->name='LAMINA';$Unidad_Medida85->state = 'ACTIVO';$Unidad_Medida85->slug = Str::uuid();$Unidad_Medida85->save();
        $Unidad_Medida86= new Unit();$Unidad_Medida86->name='LATA';$Unidad_Medida86->state = 'ACTIVO';$Unidad_Medida86->slug = Str::uuid();$Unidad_Medida86->save();
        $Unidad_Medida87= new Unit();$Unidad_Medida87->name='LETRERO';$Unidad_Medida87->state = 'ACTIVO';$Unidad_Medida87->slug = Str::uuid();$Unidad_Medida87->save();
        $Unidad_Medida88= new Unit();$Unidad_Medida88->name='LIBRA';$Unidad_Medida88->state = 'ACTIVO';$Unidad_Medida88->slug = Str::uuid();$Unidad_Medida88->save();
        $Unidad_Medida89= new Unit();$Unidad_Medida89->name='LIBRO';$Unidad_Medida89->state = 'ACTIVO';$Unidad_Medida89->slug = Str::uuid();$Unidad_Medida89->save();
        $Unidad_Medida90= new Unit();$Unidad_Medida90->name='LITROS';$Unidad_Medida90->state = 'ACTIVO';$Unidad_Medida90->slug = Str::uuid();$Unidad_Medida90->save();
        $Unidad_Medida91= new Unit();$Unidad_Medida91->name='LLANTAS';$Unidad_Medida91->state = 'ACTIVO';$Unidad_Medida91->slug = Str::uuid();$Unidad_Medida91->save();
        $Unidad_Medida92= new Unit();$Unidad_Medida92->name='LOTE';$Unidad_Medida92->state = 'ACTIVO';$Unidad_Medida92->slug = Str::uuid();$Unidad_Medida92->save();
        $Unidad_Medida93= new Unit();$Unidad_Medida93->name='MADEJA';$Unidad_Medida93->state = 'ACTIVO';$Unidad_Medida93->slug = Str::uuid();$Unidad_Medida93->save();
        $Unidad_Medida94= new Unit();$Unidad_Medida94->name='MANO DE OBRA';$Unidad_Medida94->state = 'ACTIVO';$Unidad_Medida94->slug = Str::uuid();$Unidad_Medida94->save();
        $Unidad_Medida95= new Unit();$Unidad_Medida95->name='Maple';$Unidad_Medida95->state = 'ACTIVO';$Unidad_Medida95->slug = Str::uuid();$Unidad_Medida95->save();
        $Unidad_Medida96= new Unit();$Unidad_Medida96->name='MAQUINA';$Unidad_Medida96->state = 'ACTIVO';$Unidad_Medida96->slug = Str::uuid();$Unidad_Medida96->save();
        $Unidad_Medida97= new Unit();$Unidad_Medida97->name='MATERIALES';$Unidad_Medida97->state = 'ACTIVO';$Unidad_Medida97->slug = Str::uuid();$Unidad_Medida97->save();
        $Unidad_Medida98= new Unit();$Unidad_Medida98->name='MAZO';$Unidad_Medida98->state = 'ACTIVO';$Unidad_Medida98->slug = Str::uuid();$Unidad_Medida98->save();
        $Unidad_Medida99= new Unit();$Unidad_Medida99->name='MES ';$Unidad_Medida99->state = 'ACTIVO';$Unidad_Medida99->slug = Str::uuid();$Unidad_Medida99->save();
        $Unidad_Medida100= new Unit();$Unidad_Medida100->name='MESAS ';$Unidad_Medida100->state = 'ACTIVO';$Unidad_Medida100->slug = Str::uuid();$Unidad_Medida100->save();
        $Unidad_Medida101= new Unit();$Unidad_Medida101->name='METRO ';$Unidad_Medida101->state = 'ACTIVO';$Unidad_Medida101->slug = Str::uuid();$Unidad_Medida101->save();
        $Unidad_Medida102= new Unit();$Unidad_Medida102->name='METROS CUADRADOS';$Unidad_Medida102->state = 'ACTIVO';$Unidad_Medida102->slug = Str::uuid();$Unidad_Medida102->save();
        $Unidad_Medida103= new Unit();$Unidad_Medida103->name='METROS LINEALES';$Unidad_Medida103->state = 'ACTIVO';$Unidad_Medida103->slug = Str::uuid();$Unidad_Medida103->save();
        $Unidad_Medida104= new Unit();$Unidad_Medida104->name='MOCHILAS';$Unidad_Medida104->state = 'ACTIVO';$Unidad_Medida104->slug = Str::uuid();$Unidad_Medida104->save();
        $Unidad_Medida105= new Unit();$Unidad_Medida105->name='MUESTRA';$Unidad_Medida105->state = 'ACTIVO';$Unidad_Medida105->slug = Str::uuid();$Unidad_Medida105->save();
        $Unidad_Medida106= new Unit();$Unidad_Medida106->name='OVILLO';$Unidad_Medida106->state = 'ACTIVO';$Unidad_Medida106->slug = Str::uuid();$Unidad_Medida106->save();
        $Unidad_Medida107= new Unit();$Unidad_Medida107->name='PLIEGUES ';$Unidad_Medida107->state = 'ACTIVO';$Unidad_Medida107->slug = Str::uuid();$Unidad_Medida107->save();
        $Unidad_Medida108= new Unit();$Unidad_Medida108->name='PIEZA';$Unidad_Medida108->state = 'ACTIVO';$Unidad_Medida108->slug = Str::uuid();$Unidad_Medida108->save();
        $Unidad_Medida109= new Unit();$Unidad_Medida109->name='PAGINA';$Unidad_Medida109->state = 'ACTIVO';$Unidad_Medida109->slug = Str::uuid();$Unidad_Medida109->save();
        $Unidad_Medida110= new Unit();$Unidad_Medida110->name='PAQUETE';$Unidad_Medida110->state = 'ACTIVO';$Unidad_Medida110->slug = Str::uuid();$Unidad_Medida110->save();
        $Unidad_Medida111= new Unit();$Unidad_Medida111->name='PAR';$Unidad_Medida111->state = 'ACTIVO';$Unidad_Medida111->slug = Str::uuid();$Unidad_Medida111->save();
        $Unidad_Medida112= new Unit();$Unidad_Medida112->name='PARTES';$Unidad_Medida112->state = 'ACTIVO';$Unidad_Medida112->slug = Str::uuid();$Unidad_Medida112->save();
        $Unidad_Medida113= new Unit();$Unidad_Medida113->name='PASACALLES';$Unidad_Medida113->state = 'ACTIVO';$Unidad_Medida113->slug = Str::uuid();$Unidad_Medida113->save();
        $Unidad_Medida114= new Unit();$Unidad_Medida114->name='PASAJE';$Unidad_Medida114->state = 'ACTIVO';$Unidad_Medida114->slug = Str::uuid();$Unidad_Medida114->save();
        $Unidad_Medida115= new Unit();$Unidad_Medida115->name='PASES';$Unidad_Medida115->state = 'ACTIVO';$Unidad_Medida115->slug = Str::uuid();$Unidad_Medida115->save();
        $Unidad_Medida116= new Unit();$Unidad_Medida116->name='PAZ';$Unidad_Medida116->state = 'ACTIVO';$Unidad_Medida116->slug = Str::uuid();$Unidad_Medida116->save();
        $Unidad_Medida117= new Unit();$Unidad_Medida117->name='PEDIDOS';$Unidad_Medida117->state = 'ACTIVO';$Unidad_Medida117->slug = Str::uuid();$Unidad_Medida117->save();
        $Unidad_Medida118= new Unit();$Unidad_Medida118->name='PERNO';$Unidad_Medida118->state = 'ACTIVO';$Unidad_Medida118->slug = Str::uuid();$Unidad_Medida118->save();
        $Unidad_Medida119= new Unit();$Unidad_Medida119->name='PERSONAS ';$Unidad_Medida119->state = 'ACTIVO';$Unidad_Medida119->slug = Str::uuid();$Unidad_Medida119->save();
        $Unidad_Medida120= new Unit();$Unidad_Medida120->name='PIE';$Unidad_Medida120->state = 'ACTIVO';$Unidad_Medida120->slug = Str::uuid();$Unidad_Medida120->save();
        $Unidad_Medida121= new Unit();$Unidad_Medida121->name='PIE DE PAGINAS ';$Unidad_Medida121->state = 'ACTIVO';$Unidad_Medida121->slug = Str::uuid();$Unidad_Medida121->save();
        $Unidad_Medida122= new Unit();$Unidad_Medida122->name='PIEZA';$Unidad_Medida122->state = 'ACTIVO';$Unidad_Medida122->slug = Str::uuid();$Unidad_Medida122->save();
        $Unidad_Medida123= new Unit();$Unidad_Medida123->name='PIEZA (AMBIENTE)';$Unidad_Medida123->state = 'ACTIVO';$Unidad_Medida123->slug = Str::uuid();$Unidad_Medida123->save();
        $Unidad_Medida124= new Unit();$Unidad_Medida124->name='PIOEZA';$Unidad_Medida124->state = 'ACTIVO';$Unidad_Medida124->slug = Str::uuid();$Unidad_Medida124->save();
        $Unidad_Medida125= new Unit();$Unidad_Medida125->name='PIOEZAS';$Unidad_Medida125->state = 'ACTIVO';$Unidad_Medida125->slug = Str::uuid();$Unidad_Medida125->save();
        $Unidad_Medida126= new Unit();$Unidad_Medida126->name='PLANO';$Unidad_Medida126->state = 'ACTIVO';$Unidad_Medida126->slug = Str::uuid();$Unidad_Medida126->save();
        $Unidad_Medida127= new Unit();$Unidad_Medida127->name='PLIEGUE';$Unidad_Medida127->state = 'ACTIVO';$Unidad_Medida127->slug = Str::uuid();$Unidad_Medida127->save();
        $Unidad_Medida128= new Unit();$Unidad_Medida128->name='POLIZAS';$Unidad_Medida128->state = 'ACTIVO';$Unidad_Medida128->slug = Str::uuid();$Unidad_Medida128->save();
        $Unidad_Medida129= new Unit();$Unidad_Medida129->name='POMADA';$Unidad_Medida129->state = 'ACTIVO';$Unidad_Medida129->slug = Str::uuid();$Unidad_Medida129->save();
        $Unidad_Medida130= new Unit();$Unidad_Medida130->name='POMO';$Unidad_Medida130->state = 'ACTIVO';$Unidad_Medida130->slug = Str::uuid();$Unidad_Medida130->save();
        $Unidad_Medida131= new Unit();$Unidad_Medida131->name='PORCION';$Unidad_Medida131->state = 'ACTIVO';$Unidad_Medida131->slug = Str::uuid();$Unidad_Medida131->save();
        $Unidad_Medida132= new Unit();$Unidad_Medida132->name='POTE';$Unidad_Medida132->state = 'ACTIVO';$Unidad_Medida132->slug = Str::uuid();$Unidad_Medida132->save();
        $Unidad_Medida133= new Unit();$Unidad_Medida133->name='PRECIOS';$Unidad_Medida133->state = 'ACTIVO';$Unidad_Medida133->slug = Str::uuid();$Unidad_Medida133->save();
        $Unidad_Medida134= new Unit();$Unidad_Medida134->name='PRENDAS';$Unidad_Medida134->state = 'ACTIVO';$Unidad_Medida134->slug = Str::uuid();$Unidad_Medida134->save();
        $Unidad_Medida135= new Unit();$Unidad_Medida135->name='PRESENTACIONES';$Unidad_Medida135->state = 'ACTIVO';$Unidad_Medida135->slug = Str::uuid();$Unidad_Medida135->save();
        $Unidad_Medida136= new Unit();$Unidad_Medida136->name='PUBLICACION';$Unidad_Medida136->state = 'ACTIVO';$Unidad_Medida136->slug = Str::uuid();$Unidad_Medida136->save();
        $Unidad_Medida137= new Unit();$Unidad_Medida137->name='PUNTO';$Unidad_Medida137->state = 'ACTIVO';$Unidad_Medida137->slug = Str::uuid();$Unidad_Medida137->save();
        $Unidad_Medida138= new Unit();$Unidad_Medida138->name='QUINTAL';$Unidad_Medida138->state = 'ACTIVO';$Unidad_Medida138->slug = Str::uuid();$Unidad_Medida138->save();
        $Unidad_Medida139= new Unit();$Unidad_Medida139->name='RACION ';$Unidad_Medida139->state = 'ACTIVO';$Unidad_Medida139->slug = Str::uuid();$Unidad_Medida139->save();
        $Unidad_Medida140= new Unit();$Unidad_Medida140->name='RECARGA';$Unidad_Medida140->state = 'ACTIVO';$Unidad_Medida140->slug = Str::uuid();$Unidad_Medida140->save();
        $Unidad_Medida141= new Unit();$Unidad_Medida141->name='REFRIGERIO';$Unidad_Medida141->state = 'ACTIVO';$Unidad_Medida141->slug = Str::uuid();$Unidad_Medida141->save();
        $Unidad_Medida142= new Unit();$Unidad_Medida142->name='RESMA';$Unidad_Medida142->state = 'ACTIVO';$Unidad_Medida142->slug = Str::uuid();$Unidad_Medida142->save();
        $Unidad_Medida143= new Unit();$Unidad_Medida143->name='REVISTAS';$Unidad_Medida143->state = 'ACTIVO';$Unidad_Medida143->slug = Str::uuid();$Unidad_Medida143->save();
        $Unidad_Medida144= new Unit();$Unidad_Medida144->name='ROLLER';$Unidad_Medida144->state = 'ACTIVO';$Unidad_Medida144->slug = Str::uuid();$Unidad_Medida144->save();
        $Unidad_Medida145= new Unit();$Unidad_Medida145->name='ROLLO';$Unidad_Medida145->state = 'ACTIVO';$Unidad_Medida145->slug = Str::uuid();$Unidad_Medida145->save();
        $Unidad_Medida146= new Unit();$Unidad_Medida146->name='ROSETA ';$Unidad_Medida146->state = 'ACTIVO';$Unidad_Medida146->slug = Str::uuid();$Unidad_Medida146->save();
        $Unidad_Medida147= new Unit();$Unidad_Medida147->name='SALONES';$Unidad_Medida147->state = 'ACTIVO';$Unidad_Medida147->slug = Str::uuid();$Unidad_Medida147->save();
        $Unidad_Medida148= new Unit();$Unidad_Medida148->name='SEERVICIO';$Unidad_Medida148->state = 'ACTIVO';$Unidad_Medida148->slug = Str::uuid();$Unidad_Medida148->save();
        $Unidad_Medida149= new Unit();$Unidad_Medida149->name='SEGURO';$Unidad_Medida149->state = 'ACTIVO';$Unidad_Medida149->slug = Str::uuid();$Unidad_Medida149->save();
        $Unidad_Medida150= new Unit();$Unidad_Medida150->name='SERVCIO (GLOBAL)';$Unidad_Medida150->state = 'ACTIVO';$Unidad_Medida150->slug = Str::uuid();$Unidad_Medida150->save();
        $Unidad_Medida151= new Unit();$Unidad_Medida151->name='SERVICIO';$Unidad_Medida151->state = 'ACTIVO';$Unidad_Medida151->slug = Str::uuid();$Unidad_Medida151->save();
        $Unidad_Medida152= new Unit();$Unidad_Medida152->name='SET';$Unidad_Medida152->state = 'ACTIVO';$Unidad_Medida152->slug = Str::uuid();$Unidad_Medida152->save();
        $Unidad_Medida153= new Unit();$Unidad_Medida153->name='SILLAS';$Unidad_Medida153->state = 'ACTIVO';$Unidad_Medida153->slug = Str::uuid();$Unidad_Medida153->save();
        $Unidad_Medida154= new Unit();$Unidad_Medida154->name='SISTEMA';$Unidad_Medida154->state = 'ACTIVO';$Unidad_Medida154->slug = Str::uuid();$Unidad_Medida154->save();
        $Unidad_Medida155= new Unit();$Unidad_Medida155->name='SOBRE ';$Unidad_Medida155->state = 'ACTIVO';$Unidad_Medida155->slug = Str::uuid();$Unidad_Medida155->save();
        $Unidad_Medida156= new Unit();$Unidad_Medida156->name='SOFTWARE';$Unidad_Medida156->state = 'ACTIVO';$Unidad_Medida156->slug = Str::uuid();$Unidad_Medida156->save();
        $Unidad_Medida157= new Unit();$Unidad_Medida157->name='SPOT';$Unidad_Medida157->state = 'ACTIVO';$Unidad_Medida157->slug = Str::uuid();$Unidad_Medida157->save();
        $Unidad_Medida158= new Unit();$Unidad_Medida158->name='STAND';$Unidad_Medida158->state = 'ACTIVO';$Unidad_Medida158->slug = Str::uuid();$Unidad_Medida158->save();
        $Unidad_Medida159= new Unit();$Unidad_Medida159->name='TABLERO';$Unidad_Medida159->state = 'ACTIVO';$Unidad_Medida159->slug = Str::uuid();$Unidad_Medida159->save();
        $Unidad_Medida160= new Unit();$Unidad_Medida160->name='TABLETA';$Unidad_Medida160->state = 'ACTIVO';$Unidad_Medida160->slug = Str::uuid();$Unidad_Medida160->save();
        $Unidad_Medida161= new Unit();$Unidad_Medida161->name='TACHO';$Unidad_Medida161->state = 'ACTIVO';$Unidad_Medida161->slug = Str::uuid();$Unidad_Medida161->save();
        $Unidad_Medida162= new Unit();$Unidad_Medida162->name='TALONARIO';$Unidad_Medida162->state = 'ACTIVO';$Unidad_Medida162->slug = Str::uuid();$Unidad_Medida162->save();
        $Unidad_Medida163= new Unit();$Unidad_Medida163->name='TAMBOR';$Unidad_Medida163->state = 'ACTIVO';$Unidad_Medida163->slug = Str::uuid();$Unidad_Medida163->save();
        $Unidad_Medida164= new Unit();$Unidad_Medida164->name='TAMBORES DE 200 LTS.';$Unidad_Medida164->state = 'ACTIVO';$Unidad_Medida164->slug = Str::uuid();$Unidad_Medida164->save();
        $Unidad_Medida165= new Unit();$Unidad_Medida165->name='TAMPO';$Unidad_Medida165->state = 'ACTIVO';$Unidad_Medida165->slug = Str::uuid();$Unidad_Medida165->save();
        $Unidad_Medida166= new Unit();$Unidad_Medida166->name='TARRO';$Unidad_Medida166->state = 'ACTIVO';$Unidad_Medida166->slug = Str::uuid();$Unidad_Medida166->save();
        $Unidad_Medida167= new Unit();$Unidad_Medida167->name='TERMO';$Unidad_Medida167->state = 'ACTIVO';$Unidad_Medida167->slug = Str::uuid();$Unidad_Medida167->save();
        $Unidad_Medida168= new Unit();$Unidad_Medida168->name='TONELADAS';$Unidad_Medida168->state = 'ACTIVO';$Unidad_Medida168->slug = Str::uuid();$Unidad_Medida168->save();
        $Unidad_Medida169= new Unit();$Unidad_Medida169->name='TONER';$Unidad_Medida169->state = 'ACTIVO';$Unidad_Medida169->slug = Str::uuid();$Unidad_Medida169->save();
        $Unidad_Medida170= new Unit();$Unidad_Medida170->name='TRIPTICO';$Unidad_Medida170->state = 'ACTIVO';$Unidad_Medida170->slug = Str::uuid();$Unidad_Medida170->save();
        $Unidad_Medida171= new Unit();$Unidad_Medida171->name='TRABAJADORES';$Unidad_Medida171->state = 'ACTIVO';$Unidad_Medida171->slug = Str::uuid();$Unidad_Medida171->save();
        $Unidad_Medida172= new Unit();$Unidad_Medida172->name='TUBO';$Unidad_Medida172->state = 'ACTIVO';$Unidad_Medida172->slug = Str::uuid();$Unidad_Medida172->save();
        $Unidad_Medida173= new Unit();$Unidad_Medida173->name='TURRIL ';$Unidad_Medida173->state = 'ACTIVO';$Unidad_Medida173->slug = Str::uuid();$Unidad_Medida173->save();
        $Unidad_Medida174= new Unit();$Unidad_Medida174->name='UNIDADES';$Unidad_Medida174->state = 'ACTIVO';$Unidad_Medida174->slug = Str::uuid();$Unidad_Medida174->save();
        $Unidad_Medida175= new Unit();$Unidad_Medida175->name='VALLAS';$Unidad_Medida175->state = 'ACTIVO';$Unidad_Medida175->slug = Str::uuid();$Unidad_Medida175->save();
        $Unidad_Medida176= new Unit();$Unidad_Medida176->name='VIDEO';$Unidad_Medida176->state = 'ACTIVO';$Unidad_Medida176->slug = Str::uuid();$Unidad_Medida176->save();
        $Unidad_Medida177= new Unit();$Unidad_Medida177->name='VOLUMEN ';$Unidad_Medida177->state = 'ACTIVO';$Unidad_Medida177->slug = Str::uuid();$Unidad_Medida177->save();
        $Unidad_Medida178= new Unit();$Unidad_Medida178->name='VOZ EN OFF';$Unidad_Medida178->state = 'ACTIVO';$Unidad_Medida178->slug = Str::uuid();$Unidad_Medida178->save();



    }
}
